// this has been auto generated by GenerateStdlib.java, do not modify
package com.nikodoko.javaimports.stdlib.internal;

import com.nikodoko.javaimports.parser.Import;

public class Java00Stdlib implements Stdlib {
  public Import[] getClassesFor(String identifier) {
    Import[] classes = null;
    classes = Java00StdlibChunk0.CLASSES.get(identifier);
    if (classes != null) {
      return classes;
    }
    return null;
  }
}
