// Code generated by GenerateStdlib.java. DO NOT EDIT.
package com.nikodoko.javaimports.stdlib.internal.api.v8;

import com.google.common.collect.ImmutableMap;
import com.nikodoko.javaimports.parser.Import;
import java.util.Map;

public class Java8StdlibChunk1 {
  static final Map<String, Import[]> CLASSES =
      new ImmutableMap.Builder<String, Import[]>()
          .put(
              "EMBEDDED_BY",
              new Import[] {
                new Import("EMBEDDED_BY", "javax.accessibility.AccessibleRelation", true),
              })
          .put(
              "tk_union",
              new Import[] {
                new Import("tk_union", "org.omg.CORBA.TCKind", true),
              })
          .put(
              "AlreadyConnectedException",
              new Import[] {
                new Import("AlreadyConnectedException", "java.nio.channels", false),
              })
          .put(
              "newSetFromMap",
              new Import[] {
                new Import("newSetFromMap", "java.util.Collections", true),
              })
          .put(
              "NotDirectoryException",
              new Import[] {
                new Import("NotDirectoryException", "java.nio.file", false),
              })
          .put(
              "FUSER_OVER_TEMP",
              new Import[] {
                new Import(
                    "FUSER_OVER_TEMP", "javax.print.attribute.standard.PrinterStateReason", true),
              })
          .put(
              "LayeredHighlighter",
              new Import[] {
                new Import("LayeredHighlighter", "javax.swing.text", false),
              })
          .put(
              "newOutputStream",
              new Import[] {
                new Import("newOutputStream", "java.nio.channels.Channels", true),
                new Import("newOutputStream", "java.nio.file.Files", true),
              })
          .put(
              "Popup",
              new Import[] {
                new Import("Popup", "javax.swing", false),
              })
          .put(
              "MetalTabbedPaneUI",
              new Import[] {
                new Import("MetalTabbedPaneUI", "javax.swing.plaf.metal", false),
              })
          .put(
              "BasicAttribute",
              new Import[] {
                new Import("BasicAttribute", "javax.naming.directory", false),
              })
          .put(
              "EGYPTIAN_HIEROGLYPHS",
              new Import[] {
                new Import("EGYPTIAN_HIEROGLYPHS", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "MEDIUM",
              new Import[] {
                new Import("MEDIUM", "java.text.DateFormat", true),
              })
          .put(
              "VERTICAL_ALIGN",
              new Import[] {
                new Import("VERTICAL_ALIGN", "javax.swing.text.html.CSS.Attribute", true),
              })
          .put(
              "MIN_CODE_POINT",
              new Import[] {
                new Import("MIN_CODE_POINT", "java.lang.Character", true),
              })
          .put(
              "GeneralSecurityException",
              new Import[] {
                new Import("GeneralSecurityException", "java.security", false),
              })
          .put(
              "TransactionalWriter",
              new Import[] {
                new Import("TransactionalWriter", "javax.sql.rowset.spi", false),
              })
          .put(
              "createInterleaved",
              new Import[] {
                new Import("createInterleaved", "javax.imageio.ImageTypeSpecifier", true),
              })
          .put(
              "getSystemResourceAsStream",
              new Import[] {
                new Import("getSystemResourceAsStream", "java.lang.ClassLoader", true),
              })
          .put(
              "AccountException",
              new Import[] {
                new Import("AccountException", "javax.security.auth.login", false),
              })
          .put(
              "TransferHandler",
              new Import[] {
                new Import("TransferHandler", "javax.swing", false),
              })
          .put(
              "PaintContext",
              new Import[] {
                new Import("PaintContext", "java.awt", false),
                new Import("PaintContext", "javax.swing.plaf.nimbus.AbstractRegionPainter", false),
              })
          .put(
              "installProperty",
              new Import[] {
                new Import("installProperty", "javax.swing.LookAndFeel", true),
              })
          .put(
              "TC_BLOCKDATA",
              new Import[] {
                new Import("TC_BLOCKDATA", "java.io.ObjectStreamConstants", true),
              })
          .put(
              "compare",
              new Import[] {
                new Import("compare", "java.lang.Boolean", true),
                new Import("compare", "java.lang.Byte", true),
                new Import("compare", "java.lang.Character", true),
                new Import("compare", "java.lang.Double", true),
                new Import("compare", "java.lang.Float", true),
                new Import("compare", "java.lang.Integer", true),
                new Import("compare", "java.lang.Long", true),
                new Import("compare", "java.lang.Short", true),
                new Import("compare", "java.util.Objects", true),
              })
          .put(
              "AttributeNotFoundException",
              new Import[] {
                new Import("AttributeNotFoundException", "javax.management", false),
              })
          .put(
              "Set",
              new Import[] {
                new Import("Set", "java.util", false),
              })
          .put(
              "HeadlessException",
              new Import[] {
                new Import("HeadlessException", "java.awt", false),
              })
          .put(
              "RowIdLifetime",
              new Import[] {
                new Import("RowIdLifetime", "java.sql", false),
              })
          .put(
              "ScriptEngineManager",
              new Import[] {
                new Import("ScriptEngineManager", "javax.script", false),
              })
          .put(
              "DefaultHighlighter",
              new Import[] {
                new Import("DefaultHighlighter", "javax.swing.text", false),
              })
          .put(
              "NoSuchFieldException",
              new Import[] {
                new Import("NoSuchFieldException", "java.lang", false),
              })
          .put(
              "lineSeparator",
              new Import[] {
                new Import("lineSeparator", "java.lang.System", true),
              })
          .put(
              "tk_char",
              new Import[] {
                new Import("tk_char", "org.omg.CORBA.TCKind", true),
              })
          .put(
              "SECURITY_CREDENTIALS",
              new Import[] {
                new Import("SECURITY_CREDENTIALS", "javax.naming.Context", true),
              })
          .put(
              "TOLEFT_TOBOTTOM",
              new Import[] {
                new Import(
                    "TOLEFT_TOBOTTOM",
                    "javax.print.attribute.standard.PresentationDirection",
                    true),
              })
          .put(
              "DatagramSocketImplFactory",
              new Import[] {
                new Import("DatagramSocketImplFactory", "java.net", false),
              })
          .put(
              "JdbcRowSet",
              new Import[] {
                new Import("JdbcRowSet", "javax.sql.rowset", false),
              })
          .put(
              "BadStringOperationException",
              new Import[] {
                new Import("BadStringOperationException", "javax.management", false),
              })
          .put(
              "URI_SOAP_1_2_ROLE_ULTIMATE_RECEIVER",
              new Import[] {
                new Import(
                    "URI_SOAP_1_2_ROLE_ULTIMATE_RECEIVER", "javax.xml.soap.SOAPConstants", true),
              })
          .put(
              "OutputKeys",
              new Import[] {
                new Import("OutputKeys", "javax.xml.transform", false),
              })
          .put(
              "getThreadMXBean",
              new Import[] {
                new Import("getThreadMXBean", "java.lang.management.ManagementFactory", true),
              })
          .put(
              "TYPE_5CLR",
              new Import[] {
                new Import("TYPE_5CLR", "java.awt.color.ColorSpace", true),
              })
          .put(
              "COLUMN_HEADER",
              new Import[] {
                new Import("COLUMN_HEADER", "javax.accessibility.AccessibleRole", true),
                new Import("COLUMN_HEADER", "javax.swing.ScrollPaneConstants", true),
              })
          .put(
              "getenv",
              new Import[] {
                new Import("getenv", "java.lang.System", true),
              })
          .put(
              "IdentityScope",
              new Import[] {
                new Import("IdentityScope", "java.security", false),
              })
          .put(
              "createRaisedBevelBorder",
              new Import[] {
                new Import("createRaisedBevelBorder", "javax.swing.BorderFactory", true),
              })
          .put(
              "TRACKING_TIGHT",
              new Import[] {
                new Import("TRACKING_TIGHT", "java.awt.font.TextAttribute", true),
              })
          .put(
              "SinglePixelPackedSampleModel",
              new Import[] {
                new Import("SinglePixelPackedSampleModel", "java.awt.image", false),
              })
          .put(
              "afterOffset",
              new Import[] {
                new Import("afterOffset", "java.awt.font.TextHitInfo", true),
              })
          .put(
              "AUX_SEND",
              new Import[] {
                new Import("AUX_SEND", "javax.sound.sampled.FloatControl.Type", true),
              })
          .put(
              "DragSource",
              new Import[] {
                new Import("DragSource", "java.awt.dnd", false),
              })
          .put(
              "FONT",
              new Import[] {
                new Import("FONT", "java.awt.font.TextAttribute", true),
                new Import("FONT", "javax.swing.text.html.CSS.Attribute", true),
                new Import("FONT", "javax.swing.text.html.HTML.Tag", true),
              })
          .put(
              "AbstractSelectableChannel",
              new Import[] {
                new Import("AbstractSelectableChannel", "java.nio.channels.spi", false),
              })
          .put(
              "getDefaultSSLSocketFactory",
              new Import[] {
                new Import("getDefaultSSLSocketFactory", "javax.net.ssl.HttpsURLConnection", true),
              })
          .put(
              "DragSourceMotionListener",
              new Import[] {
                new Import("DragSourceMotionListener", "java.awt.dnd", false),
              })
          .put(
              "toString",
              new Import[] {
                new Import("toString", "java.lang.Boolean", true),
                new Import("toString", "java.lang.Byte", true),
                new Import("toString", "java.lang.Character", true),
                new Import("toString", "java.lang.Double", true),
                new Import("toString", "java.lang.Float", true),
                new Import("toString", "java.lang.Integer", true),
                new Import("toString", "java.lang.Long", true),
                new Import("toString", "java.lang.Short", true),
                new Import("toString", "java.lang.invoke.MethodHandleInfo", true),
                new Import("toString", "java.lang.reflect.Modifier", true),
                new Import("toString", "java.nio.file.attribute.PosixFilePermissions", true),
                new Import("toString", "java.util.Arrays", true),
                new Import("toString", "java.util.Objects", true),
              })
          .put(
              "bitCount",
              new Import[] {
                new Import("bitCount", "java.lang.Integer", true),
                new Import("bitCount", "java.lang.Long", true),
              })
          .put(
              "JRootPane",
              new Import[] {
                new Import("JRootPane", "javax.swing", false),
              })
          .put(
              "MonitorSettingException",
              new Import[] {
                new Import("MonitorSettingException", "javax.management.monitor", false),
              })
          .put(
              "getUIInputMap",
              new Import[] {
                new Import("getUIInputMap", "javax.swing.SwingUtilities", true),
              })
          .put(
              "InputSource",
              new Import[] {
                new Import("InputSource", "org.xml.sax", false),
              })
          .put(
              "OUT_RIGHT",
              new Import[] {
                new Import("OUT_RIGHT", "java.awt.geom.Rectangle2D", true),
              })
          .put(
              "JTextComponent",
              new Import[] {
                new Import("JTextComponent", "javax.swing.text", false),
              })
          .put(
              "icHdrPlatform",
              new Import[] {
                new Import("icHdrPlatform", "java.awt.color.ICC_Profile", true),
              })
          .put(
              "DescriptorAccess",
              new Import[] {
                new Import("DescriptorAccess", "javax.management", false),
              })
          .put(
              "TYPE_GENERAL_ROTATION",
              new Import[] {
                new Import("TYPE_GENERAL_ROTATION", "java.awt.geom.AffineTransform", true),
              })
          .put(
              "CustomValue",
              new Import[] {
                new Import("CustomValue", "org.omg.CORBA.portable", false),
              })
          .put(
              "VolatileCallSite",
              new Import[] {
                new Import("VolatileCallSite", "java.lang.invoke", false),
              })
          .put(
              "UnresolvedPermission",
              new Import[] {
                new Import("UnresolvedPermission", "java.security", false),
              })
          .put(
              "EmptyStackException",
              new Import[] {
                new Import("EmptyStackException", "java.util", false),
              })
          .put(
              "div",
              new Import[] {
                new Import("div", "javax.management.Query", true),
              })
          .put(
              "ofLocalizedDate",
              new Import[] {
                new Import("ofLocalizedDate", "java.time.format.DateTimeFormatter", true),
              })
          .put(
              "DeclHandler",
              new Import[] {
                new Import("DeclHandler", "org.xml.sax.ext", false),
              })
          .put(
              "Point2D",
              new Import[] {
                new Import("Point2D", "java.awt.geom", false),
              })
          .put(
              "TextStyle",
              new Import[] {
                new Import("TextStyle", "java.time.format", false),
              })
          .put(
              "MIN_TIMEZONE_OFFSET",
              new Import[] {
                new Import("MIN_TIMEZONE_OFFSET", "javax.xml.datatype.DatatypeConstants", true),
              })
          .put(
              "PREFERRED",
              new Import[] {
                new Import("PREFERRED", "java.awt.GraphicsConfigTemplate", true),
              })
          .put(
              "ColorType",
              new Import[] {
                new Import("ColorType", "java.awt.PageAttributes", false),
                new Import("ColorType", "javax.swing.plaf.synth", false),
              })
          .put(
              "CertPathValidatorResult",
              new Import[] {
                new Import("CertPathValidatorResult", "java.security.cert", false),
              })
          .put(
              "BasicSeparatorUI",
              new Import[] {
                new Import("BasicSeparatorUI", "javax.swing.plaf.basic", false),
              })
          .put(
              "CRITICAL",
              new Import[] {
                new Import("CRITICAL", "javax.naming.ldap.Control", true),
              })
          .put(
              "Completions",
              new Import[] {
                new Import("Completions", "javax.annotation.processing", false),
              })
          .put(
              "PolicyHelper",
              new Import[] {
                new Import("PolicyHelper", "org.omg.CORBA", false),
              })
          .put(
              "DoubleBuffer",
              new Import[] {
                new Import("DoubleBuffer", "java.nio", false),
              })
          .put(
              "FilteringMode",
              new Import[] {
                new Import("FilteringMode", "java.util.Locale", false),
              })
          .put(
              "_tk_array",
              new Import[] {
                new Import("_tk_array", "org.omg.CORBA.TCKind", true),
              })
          .put(
              "isSupplementaryCodePoint",
              new Import[] {
                new Import("isSupplementaryCodePoint", "java.lang.Character", true),
              })
          .put(
              "ScheduledExecutorService",
              new Import[] {
                new Import("ScheduledExecutorService", "java.util.concurrent", false),
              })
          .put(
              "ImageInputStream",
              new Import[] {
                new Import("ImageInputStream", "javax.imageio.stream", false),
              })
          .put(
              "NoSuchFieldError",
              new Import[] {
                new Import("NoSuchFieldError", "java.lang", false),
              })
          .put(
              "createTempFile",
              new Import[] {
                new Import("createTempFile", "java.io.File", true),
                new Import("createTempFile", "java.nio.file.Files", true),
              })
          .put(
              "DiagnosticListener",
              new Import[] {
                new Import("DiagnosticListener", "javax.tools", false),
              })
          .put(
              "GraphicAttribute",
              new Import[] {
                new Import("GraphicAttribute", "java.awt.font", false),
              })
          .put(
              "getImageReadersByFormatName",
              new Import[] {
                new Import("getImageReadersByFormatName", "javax.imageio.ImageIO", true),
              })
          .put(
              "TypeInfo",
              new Import[] {
                new Import("TypeInfo", "org.w3c.dom", false),
              })
          .put(
              "URL_PKG_PREFIXES",
              new Import[] {
                new Import("URL_PKG_PREFIXES", "javax.naming.Context", true),
              })
          .put(
              "Area",
              new Import[] {
                new Import("Area", "java.awt.geom", false),
              })
          .put(
              "ActionListener",
              new Import[] {
                new Import("ActionListener", "java.awt.event", false),
              })
          .put(
              "JOB_COMPLETE",
              new Import[] {
                new Import("JOB_COMPLETE", "javax.print.event.PrintJobEvent", true),
              })
          .put(
              "PAINT",
              new Import[] {
                new Import("PAINT", "java.awt.event.PaintEvent", true),
              })
          .put(
              "ulp",
              new Import[] {
                new Import("ulp", "java.lang.Math", true),
                new Import("ulp", "java.lang.StrictMath", true),
              })
          .put(
              "asLifoQueue",
              new Import[] {
                new Import("asLifoQueue", "java.util.Collections", true),
              })
          .put(
              "JSplitPane",
              new Import[] {
                new Import("JSplitPane", "javax.swing", false),
              })
          .put(
              "BASIC_ISO_DATE",
              new Import[] {
                new Import("BASIC_ISO_DATE", "java.time.format.DateTimeFormatter", true),
              })
          .put(
              "HOUR0_FIELD",
              new Import[] {
                new Import("HOUR0_FIELD", "java.text.DateFormat", true),
              })
          .put(
              "JCOMPONENT_UI",
              new Import[] {
                new Import("JCOMPONENT_UI", "javax.print.ServiceUIFactory", true),
              })
          .put(
              "NA_10x14_ENVELOPE",
              new Import[] {
                new Import(
                    "NA_10x14_ENVELOPE", "javax.print.attribute.standard.MediaSize.NA", true),
              })
          .put(
              "CASE_INSENSITIVE_ORDER",
              new Import[] {
                new Import("CASE_INSENSITIVE_ORDER", "java.lang.String", true),
              })
          .put(
              "RelationServiceNotRegisteredException",
              new Import[] {
                new Import(
                    "RelationServiceNotRegisteredException", "javax.management.relation", false),
              })
          .put(
              "Soundbank",
              new Import[] {
                new Import("Soundbank", "javax.sound.midi", false),
              })
          .put(
              "PolicyFactory",
              new Import[] {
                new Import("PolicyFactory", "org.omg.PortableInterceptor", false),
              })
          .put(
              "BAMUM",
              new Import[] {
                new Import("BAMUM", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "isDragImageSupported",
              new Import[] {
                new Import("isDragImageSupported", "java.awt.dnd.DragSource", true),
              })
          .put(
              "isVolatile",
              new Import[] {
                new Import("isVolatile", "java.lang.reflect.Modifier", true),
              })
          .put(
              "lineLimitAttribute",
              new Import[] {
                new Import("lineLimitAttribute", "javax.swing.text.PlainDocument", true),
              })
          .put(
              "ServiceConfigurationError",
              new Import[] {
                new Import("ServiceConfigurationError", "java.util", false),
              })
          .put(
              "PipedOutputStream",
              new Import[] {
                new Import("PipedOutputStream", "java.io", false),
              })
          .put(
              "createBanded",
              new Import[] {
                new Import("createBanded", "javax.imageio.ImageTypeSpecifier", true),
              })
          .put(
              "INPUT_METHOD_LAST",
              new Import[] {
                new Import("INPUT_METHOD_LAST", "java.awt.event.InputMethodEvent", true),
              })
          .put(
              "registerServiceProvider",
              new Import[] {
                new Import("registerServiceProvider", "javax.print.PrintServiceLookup", true),
              })
          .put(
              "getTie",
              new Import[] {
                new Import("getTie", "javax.rmi.CORBA.Util", true),
              })
          .put(
              "load",
              new Import[] {
                new Import("load", "java.lang.System", true),
                new Import("load", "java.util.ServiceLoader", true),
              })
          .put(
              "GSSException",
              new Import[] {
                new Import("GSSException", "org.ietf.jgss", false),
              })
          .put(
              "LSResourceResolver",
              new Import[] {
                new Import("LSResourceResolver", "org.w3c.dom.ls", false),
              })
          .put(
              "ImageProducer",
              new Import[] {
                new Import("ImageProducer", "java.awt.image", false),
              })
          .put(
              "printInteger",
              new Import[] {
                new Import("printInteger", "javax.xml.bind.DatatypeConverter", true),
              })
          .put(
              "PBEParameterSpec",
              new Import[] {
                new Import("PBEParameterSpec", "javax.crypto.spec", false),
              })
          .put(
              "toASCII",
              new Import[] {
                new Import("toASCII", "java.net.IDN", true),
              })
          .put(
              "EXCLUSIVE",
              new Import[] {
                new Import("EXCLUSIVE", "javax.xml.crypto.dsig.CanonicalizationMethod", true),
              })
          .put(
              "FORM",
              new Import[] {
                new Import("FORM", "javax.swing.text.html.HTML.Tag", true),
              })
          .put(
              "TYPE_RASTER_SCREEN",
              new Import[] {
                new Import("TYPE_RASTER_SCREEN", "java.awt.GraphicsDevice", true),
              })
          .put(
              "getDefaultFlavorMap",
              new Import[] {
                new Import("getDefaultFlavorMap", "java.awt.datatransfer.SystemFlavorMap", true),
              })
          .put(
              "MultiLabelUI",
              new Import[] {
                new Import("MultiLabelUI", "javax.swing.plaf.multi", false),
              })
          .put(
              "TEXT_INACTIVE_TEXT",
              new Import[] {
                new Import("TEXT_INACTIVE_TEXT", "java.awt.SystemColor", true),
              })
          .put(
              "unconfigurableScheduledExecutorService",
              new Import[] {
                new Import(
                    "unconfigurableScheduledExecutorService",
                    "java.util.concurrent.Executors",
                    true),
              })
          .put(
              "RMIJRMPServerImpl",
              new Import[] {
                new Import("RMIJRMPServerImpl", "javax.management.remote.rmi", false),
              })
          .put(
              "setSpaceAbove",
              new Import[] {
                new Import("setSpaceAbove", "javax.swing.text.StyleConstants", true),
              })
          .put(
              "REMOVE_ATTRIBUTE",
              new Import[] {
                new Import("REMOVE_ATTRIBUTE", "javax.naming.directory.DirContext", true),
              })
          .put(
              "updateStyles",
              new Import[] {
                new Import("updateStyles", "javax.swing.plaf.synth.SynthLookAndFeel", true),
              })
          .put(
              "DocumentBuilder",
              new Import[] {
                new Import("DocumentBuilder", "javax.xml.parsers", false),
              })
          .put(
              "MetalBorders",
              new Import[] {
                new Import("MetalBorders", "javax.swing.plaf.metal", false),
              })
          .put(
              "procedureColumnUnknown",
              new Import[] {
                new Import("procedureColumnUnknown", "java.sql.DatabaseMetaData", true),
              })
          .put(
              "VK_ADD",
              new Import[] {
                new Import("VK_ADD", "java.awt.event.KeyEvent", true),
              })
          .put(
              "LONG_DESCRIPTION",
              new Import[] {
                new Import("LONG_DESCRIPTION", "javax.swing.Action", true),
              })
          .put(
              "ROWID",
              new Import[] {
                new Import("ROWID", "java.sql.Types", true),
              })
          .put(
              "HOUR_OF_DAY0",
              new Import[] {
                new Import("HOUR_OF_DAY0", "java.text.DateFormat.Field", true),
              })
          .put(
              "NClob",
              new Import[] {
                new Import("NClob", "java.sql", false),
              })
          .put(
              "unescapeValue",
              new Import[] {
                new Import("unescapeValue", "javax.naming.ldap.Rdn", true),
              })
          .put(
              "HOUR_OF_DAY1",
              new Import[] {
                new Import("HOUR_OF_DAY1", "java.text.DateFormat.Field", true),
              })
          .put(
              "callable",
              new Import[] {
                new Import("callable", "java.util.concurrent.Executors", true),
              })
          .put(
              "DURATION_DAYTIME",
              new Import[] {
                new Import("DURATION_DAYTIME", "javax.xml.datatype.DatatypeConstants", true),
              })
          .put(
              "lookupProviders",
              new Import[] {
                new Import("lookupProviders", "javax.imageio.spi.ServiceRegistry", true),
              })
          .put(
              "ORBIdHelper",
              new Import[] {
                new Import("ORBIdHelper", "org.omg.PortableInterceptor", false),
              })
          .put(
              "MouseMotionListener",
              new Import[] {
                new Import("MouseMotionListener", "java.awt.event", false),
              })
          .put(
              "StreamPrintService",
              new Import[] {
                new Import("StreamPrintService", "javax.print", false),
              })
          .put(
              "SoftReference",
              new Import[] {
                new Import("SoftReference", "java.lang.ref", false),
              })
          .put(
              "AccessibleExtendedTable",
              new Import[] {
                new Import("AccessibleExtendedTable", "javax.accessibility", false),
              })
          .put(
              "HOUR1_FIELD",
              new Import[] {
                new Import("HOUR1_FIELD", "java.text.DateFormat", true),
              })
          .put(
              "XmlNs",
              new Import[] {
                new Import("XmlNs", "javax.xml.bind.annotation", false),
              })
          .put(
              "text",
              new Import[] {
                new Import("text", "java.awt.SystemColor", true),
              })
          .put(
              "ARABIC_PRESENTATION_FORMS_A",
              new Import[] {
                new Import("ARABIC_PRESENTATION_FORMS_A", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "HAND_CURSOR",
              new Import[] {
                new Import("HAND_CURSOR", "java.awt.Cursor", true),
                new Import("HAND_CURSOR", "java.awt.Frame", true),
              })
          .put(
              "KeyAgreement",
              new Import[] {
                new Import("KeyAgreement", "javax.crypto", false),
              })
          .put(
              "DEFECTIVE_CREDENTIAL",
              new Import[] {
                new Import("DEFECTIVE_CREDENTIAL", "org.ietf.jgss.GSSException", true),
              })
          .put(
              "Accessible",
              new Import[] {
                new Import("Accessible", "javax.accessibility", false),
              })
          .put(
              "ROUND_DOWN",
              new Import[] {
                new Import("ROUND_DOWN", "java.math.BigDecimal", true),
              })
          .put(
              "inactiveCaptionText",
              new Import[] {
                new Import("inactiveCaptionText", "java.awt.SystemColor", true),
              })
          .put(
              "ARABIC_PRESENTATION_FORMS_B",
              new Import[] {
                new Import("ARABIC_PRESENTATION_FORMS_B", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "NO_FLUSH",
              new Import[] {
                new Import("NO_FLUSH", "java.util.zip.Deflater", true),
              })
          .put(
              "syncAll",
              new Import[] {
                new Import("syncAll", "java.lang.invoke.MutableCallSite", true),
              })
          .put(
              "TypeVisitor",
              new Import[] {
                new Import("TypeVisitor", "javax.lang.model.type", false),
              })
          .put(
              "INCLUSIVE",
              new Import[] {
                new Import("INCLUSIVE", "javax.xml.crypto.dsig.CanonicalizationMethod", true),
              })
          .put(
              "JAXBElement",
              new Import[] {
                new Import("JAXBElement", "javax.xml.bind", false),
              })
          .put(
              "_dk_all",
              new Import[] {
                new Import("_dk_all", "org.omg.CORBA.DefinitionKind", true),
              })
          .put(
              "CHECK_BOX_MENU_ITEM",
              new Import[] {
                new Import("CHECK_BOX_MENU_ITEM", "javax.swing.plaf.synth.Region", true),
              })
          .put(
              "TitleProperty",
              new Import[] {
                new Import("TitleProperty", "javax.swing.text.Document", true),
              })
          .put(
              "KEY_COLOR_RENDERING",
              new Import[] {
                new Import("KEY_COLOR_RENDERING", "java.awt.RenderingHints", true),
              })
          .put(
              "TOP",
              new Import[] {
                new Import("TOP", "javax.print.attribute.standard.MediaTray", true),
                new Import("TOP", "javax.swing.JSplitPane", true),
                new Import("TOP", "javax.swing.SwingConstants", true),
                new Import("TOP", "javax.swing.border.TitledBorder", true),
              })
          .put(
              "Printable",
              new Import[] {
                new Import("Printable", "java.awt.print", false),
              })
          .put(
              "TIMEOUT",
              new Import[] {
                new Import("TIMEOUT", "org.omg.CORBA", false),
              })
          .put(
              "ofInstant",
              new Import[] {
                new Import("ofInstant", "java.time.LocalDateTime", true),
                new Import("ofInstant", "java.time.OffsetDateTime", true),
                new Import("ofInstant", "java.time.OffsetTime", true),
                new Import("ofInstant", "java.time.ZonedDateTime", true),
              })
          .put(
              "flashTime",
              new Import[] {
                new Import("flashTime", "javax.swing.DebugGraphics", true),
              })
          .put(
              "PREVIEW_PANEL_PROPERTY",
              new Import[] {
                new Import("PREVIEW_PANEL_PROPERTY", "javax.swing.JColorChooser", true),
              })
          .put(
              "DefinitionKind",
              new Import[] {
                new Import("DefinitionKind", "org.omg.CORBA", false),
              })
          .put(
              "importedKeyInitiallyImmediate",
              new Import[] {
                new Import("importedKeyInitiallyImmediate", "java.sql.DatabaseMetaData", true),
              })
          .put(
              "FRIDAY",
              new Import[] {
                new Import("FRIDAY", "java.util.Calendar", true),
              })
          .put(
              "intBitsToFloat",
              new Import[] {
                new Import("intBitsToFloat", "java.lang.Float", true),
              })
          .put(
              "CYRILLIC",
              new Import[] {
                new Import("CYRILLIC", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "DataBufferInt",
              new Import[] {
                new Import("DataBufferInt", "java.awt.image", false),
              })
          .put(
              "ServiceDetail",
              new Import[] {
                new Import("ServiceDetail", "org.omg.CORBA", false),
              })
          .put(
              "FilteredRowSet",
              new Import[] {
                new Import("FilteredRowSet", "javax.sql.rowset", false),
              })
          .put(
              "stream",
              new Import[] {
                new Import("stream", "java.util.Arrays", true),
                new Import("stream", "java.util.stream.StreamSupport", true),
              })
          .put(
              "TEXT_INDENT",
              new Import[] {
                new Import("TEXT_INDENT", "javax.swing.text.html.CSS.Attribute", true),
              })
          .put(
              "GSSManager",
              new Import[] {
                new Import("GSSManager", "org.ietf.jgss", false),
              })
          .put(
              "AudioFileReader",
              new Import[] {
                new Import("AudioFileReader", "javax.sound.sampled.spi", false),
              })
          .put(
              "IMPLEMENTATION_VENDOR",
              new Import[] {
                new Import("IMPLEMENTATION_VENDOR", "java.util.jar.Attributes.Name", true),
              })
          .put(
              "CRLException",
              new Import[] {
                new Import("CRLException", "java.security.cert", false),
              })
          .put(
              "VK_DEAD_ABOVERING",
              new Import[] {
                new Import("VK_DEAD_ABOVERING", "java.awt.event.KeyEvent", true),
              })
          .put(
              "BreakIteratorProvider",
              new Import[] {
                new Import("BreakIteratorProvider", "java.text.spi", false),
              })
          .put(
              "ProtocolException",
              new Import[] {
                new Import("ProtocolException", "java.net", false),
                new Import("ProtocolException", "javax.xml.ws", false),
              })
          .put(
              "CollapsedStringAdapter",
              new Import[] {
                new Import("CollapsedStringAdapter", "javax.xml.bind.annotation.adapters", false),
              })
          .put(
              "PHOENICIAN",
              new Import[] {
                new Import("PHOENICIAN", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "MouseAdapter",
              new Import[] {
                new Import("MouseAdapter", "java.awt.event", false),
              })
          .put(
              "LEAD_SELECTION_PATH_PROPERTY",
              new Import[] {
                new Import("LEAD_SELECTION_PATH_PROPERTY", "javax.swing.JTree", true),
              })
          .put(
              "AuthProvider",
              new Import[] {
                new Import("AuthProvider", "java.security", false),
              })
          .put(
              "SAMPLE_RATE",
              new Import[] {
                new Import("SAMPLE_RATE", "javax.sound.sampled.FloatControl.Type", true),
              })
          .put(
              "JNDI_REBIND_ATTRIBUTE",
              new Import[] {
                new Import(
                    "JNDI_REBIND_ATTRIBUTE",
                    "javax.management.remote.rmi.RMIConnectorServer",
                    true),
              })
          .put(
              "CAPTURING_PHASE",
              new Import[] {
                new Import("CAPTURING_PHASE", "org.w3c.dom.events.Event", true),
              })
          .put(
              "BOUND_SERVER_NAME",
              new Import[] {
                new Import("BOUND_SERVER_NAME", "javax.security.sasl.Sasl", true),
              })
          .put(
              "URLClassLoader",
              new Import[] {
                new Import("URLClassLoader", "java.net", false),
              })
          .put(
              "loadClass",
              new Import[] {
                new Import("loadClass", "java.rmi.server.RMIClassLoader", true),
                new Import("loadClass", "javax.management.DefaultLoaderRepository", true),
                new Import("loadClass", "javax.management.loading.DefaultLoaderRepository", true),
                new Import("loadClass", "javax.rmi.CORBA.Util", true),
              })
          .put(
              "parameterNoNulls",
              new Import[] {
                new Import("parameterNoNulls", "java.sql.ParameterMetaData", true),
              })
          .put(
              "CPE",
              new Import[] {
                new Import("CPE", "javax.naming.spi.NamingManager", true),
              })
          .put(
              "SwingWorker",
              new Import[] {
                new Import("SwingWorker", "javax.swing", false),
              })
          .put(
              "LineMetrics",
              new Import[] {
                new Import("LineMetrics", "java.awt.font", false),
              })
          .put(
              "getBorder",
              new Import[] {
                new Import("getBorder", "javax.swing.UIManager", true),
              })
          .put(
              "CHANNEL_PRESSURE",
              new Import[] {
                new Import("CHANNEL_PRESSURE", "javax.sound.midi.ShortMessage", true),
              })
          .put(
              "TC_EXCEPTION",
              new Import[] {
                new Import("TC_EXCEPTION", "java.io.ObjectStreamConstants", true),
              })
          .put(
              "newInputStream",
              new Import[] {
                new Import("newInputStream", "java.nio.channels.Channels", true),
                new Import("newInputStream", "java.nio.file.Files", true),
              })
          .put(
              "not_object",
              new Import[] {
                new Import(
                    "not_object", "org.omg.CosNaming.NamingContextPackage.NotFoundReason", true),
              })
          .put(
              "tk_enum",
              new Import[] {
                new Import("tk_enum", "org.omg.CORBA.TCKind", true),
              })
          .put(
              "Void",
              new Import[] {
                new Import("Void", "java.lang", false),
              })
          .put(
              "SocketAddress",
              new Import[] {
                new Import("SocketAddress", "java.net", false),
              })
          .put(
              "LookAndFeelInfo",
              new Import[] {
                new Import("LookAndFeelInfo", "javax.swing.UIManager", false),
              })
          .put(
              "Box",
              new Import[] {
                new Import("Box", "javax.swing", false),
              })
          .put(
              "PlainDocument",
              new Import[] {
                new Import("PlainDocument", "javax.swing.text", false),
              })
          .put(
              "separator",
              new Import[] {
                new Import("separator", "java.io.File", true),
              })
          .put(
              "tabSizeAttribute",
              new Import[] {
                new Import("tabSizeAttribute", "javax.swing.text.PlainDocument", true),
              })
          .put(
              "getForeground",
              new Import[] {
                new Import("getForeground", "javax.swing.text.StyleConstants", true),
              })
          .put(
              "CaretListener",
              new Import[] {
                new Import("CaretListener", "javax.swing.event", false),
              })
          .put(
              "createBlackLineBorder",
              new Import[] {
                new Import("createBlackLineBorder", "javax.swing.border.LineBorder", true),
              })
          .put(
              "OpenMBeanConstructorInfoSupport",
              new Import[] {
                new Import("OpenMBeanConstructorInfoSupport", "javax.management.openmbean", false),
              })
          .put(
              "Collection",
              new Import[] {
                new Import("Collection", "java.util", false),
              })
          .put(
              "ToIntFunction",
              new Import[] {
                new Import("ToIntFunction", "java.util.function", false),
              })
          .put(
              "THAI",
              new Import[] {
                new Import("THAI", "java.awt.font.NumericShaper", true),
                new Import("THAI", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "CRL",
              new Import[] {
                new Import("CRL", "java.security.cert", false),
              })
          .put(
              "loadKeyBindings",
              new Import[] {
                new Import("loadKeyBindings", "javax.swing.LookAndFeel", true),
              })
          .put(
              "RANGE",
              new Import[] {
                new Import("RANGE", "java.awt.JobAttributes.DefaultSelectionType", true),
              })
          .put(
              "PLUS",
              new Import[] {
                new Import("PLUS", "javax.management.Query", true),
              })
          .put(
              "NO_LOCATION",
              new Import[] {
                new Import("NO_LOCATION", "javax.xml.bind.annotation.XmlSchema", true),
              })
          .put(
              "SCROLL_LINE_DOWN",
              new Import[] {
                new Import("SCROLL_LINE_DOWN", "java.awt.Event", true),
              })
          .put(
              "HEAD",
              new Import[] {
                new Import("HEAD", "javax.swing.text.html.HTML.Tag", true),
              })
          .put(
              "ObjectInputValidation",
              new Import[] {
                new Import("ObjectInputValidation", "java.io", false),
              })
          .put(
              "STORED",
              new Import[] {
                new Import("STORED", "java.util.zip.ZipEntry", true),
                new Import("STORED", "java.util.zip.ZipOutputStream", true),
              })
          .put(
              "Src",
              new Import[] {
                new Import("Src", "java.awt.AlphaComposite", true),
              })
          .put(
              "isISOControl",
              new Import[] {
                new Import("isISOControl", "java.lang.Character", true),
              })
          .put(
              "VK_DEAD_MACRON",
              new Import[] {
                new Import("VK_DEAD_MACRON", "java.awt.event.KeyEvent", true),
              })
          .put(
              "DIRECTIONALITY_ARABIC_NUMBER",
              new Import[] {
                new Import("DIRECTIONALITY_ARABIC_NUMBER", "java.lang.Character", true),
              })
          .put(
              "ObjectAlreadyActiveHelper",
              new Import[] {
                new Import("ObjectAlreadyActiveHelper", "org.omg.PortableServer.POAPackage", false),
              })
          .put(
              "PolicyErrorCodeHelper",
              new Import[] {
                new Import("PolicyErrorCodeHelper", "org.omg.CORBA", false),
              })
          .put(
              "Clear",
              new Import[] {
                new Import("Clear", "java.awt.AlphaComposite", true),
              })
          .put(
              "IMPLICIT_ACTIVATION_POLICY_ID",
              new Import[] {
                new Import("IMPLICIT_ACTIVATION_POLICY_ID", "org.omg.PortableServer", false),
              })
          .put(
              "SynthUI",
              new Import[] {
                new Import("SynthUI", "javax.swing.plaf.synth", false),
              })
          .put(
              "FINAL_QUOTE_PUNCTUATION",
              new Import[] {
                new Import("FINAL_QUOTE_PUNCTUATION", "java.lang.Character", true),
              })
          .put(
              "ThaiBuddhistChronology",
              new Import[] {
                new Import("ThaiBuddhistChronology", "java.time.chrono", false),
              })
          .put(
              "WriteAbortedException",
              new Import[] {
                new Import("WriteAbortedException", "java.io", false),
              })
          .put(
              "PrinterInfo",
              new Import[] {
                new Import("PrinterInfo", "javax.print.attribute.standard", false),
              })
          .put(
              "CLASS_COLORSPACECONVERSION",
              new Import[] {
                new Import("CLASS_COLORSPACECONVERSION", "java.awt.color.ICC_Profile", true),
              })
          .put(
              "ConnectException",
              new Import[] {
                new Import("ConnectException", "java.net", false),
                new Import("ConnectException", "java.rmi", false),
              })
          .put(
              "MTOM",
              new Import[] {
                new Import("MTOM", "javax.xml.ws.soap", false),
              })
          .put(
              "CSS",
              new Import[] {
                new Import("CSS", "javax.swing.text.html", false),
              })
          .put(
              "BeanContextProxy",
              new Import[] {
                new Import("BeanContextProxy", "java.beans.beancontext", false),
              })
          .put(
              "COMPLETED_NO",
              new Import[] {
                new Import("COMPLETED_NO", "org.omg.CORBA.CompletionStatus", true),
              })
          .put(
              "KANNADA",
              new Import[] {
                new Import("KANNADA", "java.awt.font.NumericShaper", true),
                new Import("KANNADA", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "XPATH2",
              new Import[] {
                new Import("XPATH2", "javax.xml.crypto.dsig.Transform", true),
              })
          .put(
              "XPathFunction",
              new Import[] {
                new Import("XPathFunction", "javax.xml.xpath", false),
              })
          .put(
              "insertArguments",
              new Import[] {
                new Import("insertArguments", "java.lang.invoke.MethodHandles", true),
              })
          .put(
              "TransferSupport",
              new Import[] {
                new Import("TransferSupport", "javax.swing.TransferHandler", false),
              })
          .put(
              "getAvailableChronologies",
              new Import[] {
                new Import("getAvailableChronologies", "java.time.chrono.Chronology", true),
              })
          .put(
              "JToolBar",
              new Import[] {
                new Import("JToolBar", "javax.swing", false),
              })
          .put(
              "MIN_VALUE",
              new Import[] {
                new Import("MIN_VALUE", "java.lang.Byte", true),
                new Import("MIN_VALUE", "java.lang.Character", true),
                new Import("MIN_VALUE", "java.lang.Double", true),
                new Import("MIN_VALUE", "java.lang.Float", true),
                new Import("MIN_VALUE", "java.lang.Integer", true),
                new Import("MIN_VALUE", "java.lang.Long", true),
                new Import("MIN_VALUE", "java.lang.Short", true),
                new Import("MIN_VALUE", "java.time.Year", true),
              })
          .put(
              "isSubscript",
              new Import[] {
                new Import("isSubscript", "javax.swing.text.StyleConstants", true),
              })
          .put(
              "getTag",
              new Import[] {
                new Import("getTag", "javax.swing.text.html.HTML", true),
              })
          .put(
              "COMBINING_MARKS_FOR_SYMBOLS",
              new Import[] {
                new Import("COMBINING_MARKS_FOR_SYMBOLS", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "MetalSliderUI",
              new Import[] {
                new Import("MetalSliderUI", "javax.swing.plaf.metal", false),
              })
          .put(
              "LINE_OUT",
              new Import[] {
                new Import("LINE_OUT", "javax.sound.sampled.Port.Info", true),
              })
          .put(
              "SocketOption",
              new Import[] {
                new Import("SocketOption", "java.net", false),
              })
          .put(
              "ServiceDelegate",
              new Import[] {
                new Import("ServiceDelegate", "javax.xml.ws.spi", false),
              })
          .put(
              "Track",
              new Import[] {
                new Import("Track", "javax.sound.midi", false),
              })
          .put(
              "JDesktopPane",
              new Import[] {
                new Import("JDesktopPane", "javax.swing", false),
              })
          .put(
              "Owner",
              new Import[] {
                new Import("Owner", "java.security.acl", false),
              })
          .put(
              "ZoneRulesException",
              new Import[] {
                new Import("ZoneRulesException", "java.time.zone", false),
              })
          .put(
              "JTextArea",
              new Import[] {
                new Import("JTextArea", "javax.swing", false),
              })
          .put(
              "Configuration",
              new Import[] {
                new Import("Configuration", "javax.security.auth.login", false),
              })
          .put(
              "lastInMonth",
              new Import[] {
                new Import("lastInMonth", "java.time.temporal.TemporalAdjusters", true),
              })
          .put(
              "DefaultKeyTypedAction",
              new Import[] {
                new Import("DefaultKeyTypedAction", "javax.swing.text.DefaultEditorKit", false),
              })
          .put(
              "Naming",
              new Import[] {
                new Import("Naming", "java.rmi", false),
              })
          .put(
              "SpinnerModel",
              new Import[] {
                new Import("SpinnerModel", "javax.swing", false),
              })
          .put(
              "INFORMATION_DIALOG",
              new Import[] {
                new Import("INFORMATION_DIALOG", "javax.swing.JRootPane", true),
              })
          .put(
              "XmlList",
              new Import[] {
                new Import("XmlList", "javax.xml.bind.annotation", false),
              })
          .put(
              "SAXException",
              new Import[] {
                new Import("SAXException", "org.xml.sax", false),
              })
          .put(
              "CASE_INSENSITIVE",
              new Import[] {
                new Import("CASE_INSENSITIVE", "java.util.regex.Pattern", true),
              })
          .put(
              "DOMURIReference",
              new Import[] {
                new Import("DOMURIReference", "javax.xml.crypto.dom", false),
              })
          .put(
              "ID_ASSIGNMENT_POLICY_ID",
              new Import[] {
                new Import("ID_ASSIGNMENT_POLICY_ID", "org.omg.PortableServer", false),
              })
          .put(
              "PRESSED_ICON_CHANGED_PROPERTY",
              new Import[] {
                new Import("PRESSED_ICON_CHANGED_PROPERTY", "javax.swing.AbstractButton", true),
              })
          .put(
              "GSSName",
              new Import[] {
                new Import("GSSName", "org.ietf.jgss", false),
              })
          .put(
              "VALUE_FRACTIONALMETRICS_ON",
              new Import[] {
                new Import("VALUE_FRACTIONALMETRICS_ON", "java.awt.RenderingHints", true),
              })
          .put(
              "TEXT_HTML_UTF_8",
              new Import[] {
                new Import("TEXT_HTML_UTF_8", "javax.print.DocFlavor.BYTE_ARRAY", true),
                new Import("TEXT_HTML_UTF_8", "javax.print.DocFlavor.INPUT_STREAM", true),
                new Import("TEXT_HTML_UTF_8", "javax.print.DocFlavor.URL", true),
              })
          .put(
              "StreamResult",
              new Import[] {
                new Import("StreamResult", "javax.xml.transform.stream", false),
              })
          .put(
              "selectionDownAction",
              new Import[] {
                new Import("selectionDownAction", "javax.swing.text.DefaultEditorKit", true),
              })
          .put(
              "doLookup",
              new Import[] {
                new Import("doLookup", "javax.naming.InitialContext", true),
              })
          .put(
              "IDENTITY",
              new Import[] {
                new Import("IDENTITY", "java.awt.font.TransformAttribute", true),
              })
          .put(
              "ofSecondOfDay",
              new Import[] {
                new Import("ofSecondOfDay", "java.time.LocalTime", true),
              })
          .put(
              "ComboPopup",
              new Import[] {
                new Import("ComboPopup", "javax.swing.plaf.basic", false),
              })
          .put(
              "MultiTextUI",
              new Import[] {
                new Import("MultiTextUI", "javax.swing.plaf.multi", false),
              })
          .put(
              "DELEGATE_NAME",
              new Import[] {
                new Import("DELEGATE_NAME", "javax.management.MBeanServerDelegate", true),
              })
          .put(
              "JPasswordField",
              new Import[] {
                new Import("JPasswordField", "javax.swing", false),
              })
          .put(
              "PRIVATE_USE_AREA",
              new Import[] {
                new Import("PRIVATE_USE_AREA", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "HttpCookie",
              new Import[] {
                new Import("HttpCookie", "java.net", false),
              })
          .put(
              "isReadable",
              new Import[] {
                new Import("isReadable", "java.nio.file.Files", true),
              })
          .put(
              "getTreeControlIcon",
              new Import[] {
                new Import("getTreeControlIcon", "javax.swing.plaf.metal.MetalIconFactory", true),
              })
          .put(
              "GENERAL_PUNCTUATION",
              new Import[] {
                new Import("GENERAL_PUNCTUATION", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "BeanContextServicesListener",
              new Import[] {
                new Import("BeanContextServicesListener", "java.beans.beancontext", false),
              })
          .put(
              "JAXBPermission",
              new Import[] {
                new Import("JAXBPermission", "javax.xml.bind", false),
              })
          .put(
              "PolicyHolder",
              new Import[] {
                new Import("PolicyHolder", "org.omg.CORBA", false),
              })
          .put(
              "BasicArrowButton",
              new Import[] {
                new Import("BasicArrowButton", "javax.swing.plaf.basic", false),
              })
          .put(
              "tk_ushort",
              new Import[] {
                new Import("tk_ushort", "org.omg.CORBA.TCKind", true),
              })
          .put(
              "DirectColorModel",
              new Import[] {
                new Import("DirectColorModel", "java.awt.image", false),
              })
          .put(
              "RAISED",
              new Import[] {
                new Import("RAISED", "javax.swing.border.BevelBorder", true),
                new Import("RAISED", "javax.swing.border.EtchedBorder", true),
              })
          .put(
              "ConcurrentNavigableMap",
              new Import[] {
                new Import("ConcurrentNavigableMap", "java.util.concurrent", false),
              })
          .put(
              "selectBestTextFlavor",
              new Import[] {
                new Import("selectBestTextFlavor", "java.awt.datatransfer.DataFlavor", true),
              })
          .put(
              "REF_MBEAN_NOT_REGISTERED",
              new Import[] {
                new Import(
                    "REF_MBEAN_NOT_REGISTERED", "javax.management.relation.RoleStatus", true),
              })
          .put(
              "DecimalFormatSymbols",
              new Import[] {
                new Import("DecimalFormatSymbols", "java.text", false),
              })
          .put(
              "getProxyClass",
              new Import[] {
                new Import("getProxyClass", "java.lang.reflect.Proxy", true),
              })
          .put(
              "NamingEvent",
              new Import[] {
                new Import("NamingEvent", "javax.naming.event", false),
              })
          .put(
              "getInternalFrameDefaultMenuIcon",
              new Import[] {
                new Import(
                    "getInternalFrameDefaultMenuIcon",
                    "javax.swing.plaf.metal.MetalIconFactory",
                    true),
              })
          .put(
              "icSigLuvData",
              new Import[] {
                new Import("icSigLuvData", "java.awt.color.ICC_Profile", true),
              })
          .put(
              "icSigBToA1Tag",
              new Import[] {
                new Import("icSigBToA1Tag", "java.awt.color.ICC_Profile", true),
              })
          .put(
              "RuntimeMXBean",
              new Import[] {
                new Import("RuntimeMXBean", "java.lang.management", false),
              })
          .put(
              "FormatStyle",
              new Import[] {
                new Import("FormatStyle", "java.time.format", false),
              })
          .put(
              "MemoryUsage",
              new Import[] {
                new Import("MemoryUsage", "java.lang.management", false),
              })
          .put(
              "SerializedLambda",
              new Import[] {
                new Import("SerializedLambda", "java.lang.invoke", false),
              })
          .put(
              "FOREGROUND",
              new Import[] {
                new Import("FOREGROUND", "java.awt.font.TextAttribute", true),
                new Import("FOREGROUND", "javax.swing.plaf.synth.ColorType", true),
              })
          .put(
              "FONT_CHANGE_BIGGER",
              new Import[] {
                new Import("FONT_CHANGE_BIGGER", "javax.swing.text.html.HTMLEditorKit", true),
              })
          .put(
              "UTFDataFormatException",
              new Import[] {
                new Import("UTFDataFormatException", "java.io", false),
              })
          .put(
              "ALLBITS",
              new Import[] {
                new Import("ALLBITS", "java.awt.image.ImageObserver", true),
              })
          .put(
              "CompletionException",
              new Import[] {
                new Import("CompletionException", "java.util.concurrent", false),
              })
          .put(
              "Event",
              new Import[] {
                new Import("Event", "java.awt", false),
                new Import("Event", "org.w3c.dom.events", false),
              })
          .put(
              "STRING",
              new Import[] {
                new Import("STRING", "javax.management.openmbean.SimpleType", true),
                new Import("STRING", "javax.print.DocFlavor", false),
                new Import("STRING", "javax.xml.xpath.XPathConstants", true),
              })
          .put(
              "getDefaultHostnameVerifier",
              new Import[] {
                new Import("getDefaultHostnameVerifier", "javax.net.ssl.HttpsURLConnection", true),
              })
          .put(
              "TEXT_HTML",
              new Import[] {
                new Import("TEXT_HTML", "javax.print.DocFlavor.CHAR_ARRAY", true),
                new Import("TEXT_HTML", "javax.print.DocFlavor.READER", true),
                new Import("TEXT_HTML", "javax.print.DocFlavor.STRING", true),
              })
          .put(
              "SimpleJavaFileObject",
              new Import[] {
                new Import("SimpleJavaFileObject", "javax.tools", false),
              })
          .put(
              "REF_CURSOR",
              new Import[] {
                new Import("REF_CURSOR", "java.sql.Types", true),
              })
          .put(
              "QUARTER_OF_YEAR",
              new Import[] {
                new Import("QUARTER_OF_YEAR", "java.time.temporal.IsoFields", true),
              })
          .put(
              "tickMinutes",
              new Import[] {
                new Import("tickMinutes", "java.time.Clock", true),
              })
          .put(
              "TMNOFLAGS",
              new Import[] {
                new Import("TMNOFLAGS", "javax.transaction.xa.XAResource", true),
              })
          .put(
              "DOWN_CYCLE_TRAVERSAL_KEYS",
              new Import[] {
                new Import("DOWN_CYCLE_TRAVERSAL_KEYS", "java.awt.KeyboardFocusManager", true),
              })
          .put(
              "TYPE_NEAREST_NEIGHBOR",
              new Import[] {
                new Import("TYPE_NEAREST_NEIGHBOR", "java.awt.image.AffineTransformOp", true),
              })
          .put(
              "JAXBSource",
              new Import[] {
                new Import("JAXBSource", "javax.xml.bind.util", false),
              })
          .put(
              "PrintRequestAttributeSet",
              new Import[] {
                new Import("PrintRequestAttributeSet", "javax.print.attribute", false),
              })
          .put(
              "UNSPECIFIED_EVENT_TYPE_ERR",
              new Import[] {
                new Import("UNSPECIFIED_EVENT_TYPE_ERR", "org.w3c.dom.events.EventException", true),
              })
          .put(
              "unexportObject",
              new Import[] {
                new Import("unexportObject", "java.rmi.activation.Activatable", true),
                new Import("unexportObject", "java.rmi.server.UnicastRemoteObject", true),
                new Import("unexportObject", "javax.rmi.PortableRemoteObject", true),
                new Import("unexportObject", "javax.rmi.CORBA.Util", true),
              })
          .put(
              "FIELD_COUNT",
              new Import[] {
                new Import("FIELD_COUNT", "java.util.Calendar", true),
              })
          .put(
              "SEVERITY_WARNING",
              new Import[] {
                new Import("SEVERITY_WARNING", "org.w3c.dom.DOMError", true),
              })
          .put(
              "ENTITIES",
              new Import[] {
                new Import("ENTITIES", "javax.swing.text.html.parser.DTDConstants", true),
              })
          .put(
              "WeekFields",
              new Import[] {
                new Import("WeekFields", "java.time.temporal", false),
              })
          .put(
              "getMixer",
              new Import[] {
                new Import("getMixer", "javax.sound.sampled.AudioSystem", true),
              })
          .put(
              "TextComponent",
              new Import[] {
                new Import("TextComponent", "java.awt", false),
              })
          .put(
              "RETURN_GENERATED_KEYS",
              new Import[] {
                new Import("RETURN_GENERATED_KEYS", "java.sql.Statement", true),
              })
          .put(
              "MalformedObjectNameException",
              new Import[] {
                new Import("MalformedObjectNameException", "javax.management", false),
              })
          .put(
              "NUMBER",
              new Import[] {
                new Import("NUMBER", "javax.swing.text.html.parser.DTDConstants", true),
                new Import("NUMBER", "javax.xml.xpath.XPathConstants", true),
              })
          .put(
              "PrivilegedActionException",
              new Import[] {
                new Import("PrivilegedActionException", "java.security", false),
              })
          .put(
              "TUESDAY",
              new Import[] {
                new Import("TUESDAY", "java.util.Calendar", true),
              })
          .put(
              "PresentationDirection",
              new Import[] {
                new Import("PresentationDirection", "javax.print.attribute.standard", false),
              })
          .put(
              "MOUSE_DOWN",
              new Import[] {
                new Import("MOUSE_DOWN", "java.awt.Event", true),
              })
          .put(
              "ByteLookupTable",
              new Import[] {
                new Import("ByteLookupTable", "java.awt.image", false),
              })
          .put(
              "NoSuchMethodError",
              new Import[] {
                new Import("NoSuchMethodError", "java.lang", false),
              })
          .put(
              "MBeanServerForwarder",
              new Import[] {
                new Import("MBeanServerForwarder", "javax.management.remote", false),
              })
          .put(
              "getDateTimeInstance",
              new Import[] {
                new Import("getDateTimeInstance", "java.text.DateFormat", true),
              })
          .put(
              "EventListenerProxy",
              new Import[] {
                new Import("EventListenerProxy", "java.util", false),
              })
          .put(
              "getLookAndFeelDefaults",
              new Import[] {
                new Import("getLookAndFeelDefaults", "javax.swing.UIManager", true),
              })
          .put(
              "MEETEI_MAYEK",
              new Import[] {
                new Import("MEETEI_MAYEK", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "ECPublicKey",
              new Import[] {
                new Import("ECPublicKey", "java.security.interfaces", false),
              })
          .put(
              "RUNTIME_ERROR",
              new Import[] {
                new Import("RUNTIME_ERROR", "javax.management.monitor.MonitorNotification", true),
              })
          .put(
              "LIGATURES",
              new Import[] {
                new Import("LIGATURES", "java.awt.font.TextAttribute", true),
              })
          .put(
              "BeanContextServiceRevokedListener",
              new Import[] {
                new Import("BeanContextServiceRevokedListener", "java.beans.beancontext", false),
              })
          .put(
              "AsyncHandler",
              new Import[] {
                new Import("AsyncHandler", "javax.xml.ws", false),
              })
          .put(
              "getKeyText",
              new Import[] {
                new Import("getKeyText", "java.awt.event.KeyEvent", true),
              })
          .put(
              "REF_putField",
              new Import[] {
                new Import("REF_putField", "java.lang.invoke.MethodHandleInfo", true),
              })
          .put(
              "Time",
              new Import[] {
                new Import("Time", "java.sql", false),
              })
          .put(
              "HTTP_VERSION",
              new Import[] {
                new Import("HTTP_VERSION", "java.net.HttpURLConnection", true),
              })
          .put(
              "SPIN_BOX",
              new Import[] {
                new Import("SPIN_BOX", "javax.accessibility.AccessibleRole", true),
              })
          .put(
              "NameDynAnyPairHelper",
              new Import[] {
                new Import("NameDynAnyPairHelper", "org.omg.DynamicAny", false),
              })
          .put(
              "showDialog",
              new Import[] {
                new Import("showDialog", "javax.swing.JColorChooser", true),
              })
          .put(
              "DeflaterOutputStream",
              new Import[] {
                new Import("DeflaterOutputStream", "java.util.zip", false),
              })
          .put(
              "PASSWORD_PROPERTY",
              new Import[] {
                new Import("PASSWORD_PROPERTY", "javax.xml.ws.BindingProvider", true),
              })
          .put(
              "UncaughtExceptionHandler",
              new Import[] {
                new Import("UncaughtExceptionHandler", "java.lang.Thread", false),
              })
          .put(
              "publicLookup",
              new Import[] {
                new Import("publicLookup", "java.lang.invoke.MethodHandles", true),
              })
          .put(
              "ThreadPolicyOperations",
              new Import[] {
                new Import("ThreadPolicyOperations", "org.omg.PortableServer", false),
              })
          .put(
              "primaryOrder",
              new Import[] {
                new Import("primaryOrder", "java.text.CollationElementIterator", true),
              })
          .put(
              "CHILD_POLICY_EMPTY",
              new Import[] {
                new Import("CHILD_POLICY_EMPTY", "javax.imageio.metadata.IIOMetadataFormat", true),
              })
          .put(
              "IntPredicate",
              new Import[] {
                new Import("IntPredicate", "java.util.function", false),
              })
          .put(
              "FileImageOutputStream",
              new Import[] {
                new Import("FileImageOutputStream", "javax.imageio.stream", false),
              })
          .put(
              "TextSyntax",
              new Import[] {
                new Import("TextSyntax", "javax.print.attribute", false),
              })
          .put(
              "JavaCompiler",
              new Import[] {
                new Import("JavaCompiler", "javax.tools", false),
              })
          .put(
              "Flush3DBorder",
              new Import[] {
                new Import("Flush3DBorder", "javax.swing.plaf.metal.MetalBorders", false),
              })
          .put(
              "_COMPLETED_YES",
              new Import[] {
                new Import("_COMPLETED_YES", "org.omg.CORBA.CompletionStatus", true),
              })
          .put(
              "ByteArrayOutputStream",
              new Import[] {
                new Import("ByteArrayOutputStream", "java.io", false),
              })
          .put(
              "REPORT",
              new Import[] {
                new Import("REPORT", "java.nio.charset.CodingErrorAction", true),
                new Import("REPORT", "javax.print.attribute.standard.Severity", true),
              })
          .put(
              "setComponent",
              new Import[] {
                new Import("setComponent", "javax.swing.text.StyleConstants", true),
              })
          .put(
              "CertPath",
              new Import[] {
                new Import("CertPath", "java.security.cert", false),
              })
          .put(
              "X509CRLSelector",
              new Import[] {
                new Import("X509CRLSelector", "java.security.cert", false),
              })
          .put(
              "XmlAdapter",
              new Import[] {
                new Import("XmlAdapter", "javax.xml.bind.annotation.adapters", false),
              })
          .put(
              "ADJUSTMENT_FIRST",
              new Import[] {
                new Import("ADJUSTMENT_FIRST", "java.awt.event.AdjustmentEvent", true),
              })
          .put(
              "EventException",
              new Import[] {
                new Import("EventException", "org.w3c.dom.events", false),
              })
          .put(
              "_tk_octet",
              new Import[] {
                new Import("_tk_octet", "org.omg.CORBA.TCKind", true),
              })
          .put(
              "PSource",
              new Import[] {
                new Import("PSource", "javax.crypto.spec", false),
              })
          .put(
              "NORM_PRIORITY",
              new Import[] {
                new Import("NORM_PRIORITY", "java.lang.Thread", true),
              })
          .put(
              "MAX_NAME_LENGTH",
              new Import[] {
                new Import("MAX_NAME_LENGTH", "java.util.prefs.Preferences", true),
              })
          .put(
              "KeyAlreadyExistsException",
              new Import[] {
                new Import("KeyAlreadyExistsException", "javax.management.openmbean", false),
              })
          .put(
              "SESSION_MAINTAIN_PROPERTY",
              new Import[] {
                new Import("SESSION_MAINTAIN_PROPERTY", "javax.xml.ws.BindingProvider", true),
              })
          .put(
              "HINTS_OBSERVED",
              new Import[] {
                new Import("HINTS_OBSERVED", "java.awt.image.renderable.RenderableImage", true),
              })
          .put(
              "checkedList",
              new Import[] {
                new Import("checkedList", "java.util.Collections", true),
              })
          .put(
              "Type",
              new Import[] {
                new Import("Type", "java.awt.Window", false),
                new Import("Type", "java.lang.ProcessBuilder.Redirect", false),
                new Import("Type", "java.lang.reflect", false),
                new Import("Type", "java.net.Proxy", false),
                new Import("Type", "java.security.KeyRep", false),
                new Import("Type", "javax.sound.sampled.AudioFileFormat", false),
                new Import("Type", "javax.sound.sampled.BooleanControl", false),
                new Import("Type", "javax.sound.sampled.CompoundControl", false),
                new Import("Type", "javax.sound.sampled.Control", false),
                new Import("Type", "javax.sound.sampled.EnumControl", false),
                new Import("Type", "javax.sound.sampled.FloatControl", false),
                new Import("Type", "javax.sound.sampled.LineEvent", false),
                new Import("Type", "javax.swing.event.RowSorterEvent", false),
              })
          .put(
              "TAB",
              new Import[] {
                new Import("TAB", "java.awt.Event", true),
              })
          .put(
              "Characteristics",
              new Import[] {
                new Import("Characteristics", "java.util.stream.Collector", false),
              })
          .put(
              "SignatureProperties",
              new Import[] {
                new Import("SignatureProperties", "javax.xml.crypto.dsig", false),
              })
          .put(
              "icSigSpace3CLR",
              new Import[] {
                new Import("icSigSpace3CLR", "java.awt.color.ICC_Profile", true),
              })
          .put(
              "IntToLongFunction",
              new Import[] {
                new Import("IntToLongFunction", "java.util.function", false),
              })
          .put(
              "MissingFormatWidthException",
              new Import[] {
                new Import("MissingFormatWidthException", "java.util", false),
              })
          .put(
              "OpenMBeanAttributeInfoSupport",
              new Import[] {
                new Import("OpenMBeanAttributeInfoSupport", "javax.management.openmbean", false),
              })
          .put(
              "ButtonModel",
              new Import[] {
                new Import("ButtonModel", "javax.swing", false),
              })
          .put(
              "NVList",
              new Import[] {
                new Import("NVList", "org.omg.CORBA", false),
              })
          .put(
              "KHMER",
              new Import[] {
                new Import("KHMER", "java.awt.font.NumericShaper", true),
                new Import("KHMER", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "MultiTableUI",
              new Import[] {
                new Import("MultiTableUI", "javax.swing.plaf.multi", false),
              })
          .put(
              "UNDERLINE_LOW_GRAY",
              new Import[] {
                new Import("UNDERLINE_LOW_GRAY", "java.awt.font.TextAttribute", true),
              })
          .put(
              "PagedResultsResponseControl",
              new Import[] {
                new Import("PagedResultsResponseControl", "javax.naming.ldap", false),
              })
          .put(
              "RoundingMode",
              new Import[] {
                new Import("RoundingMode", "java.math", false),
              })
          .put(
              "SELECTION_MODE_PROPERTY",
              new Import[] {
                new Import(
                    "SELECTION_MODE_PROPERTY", "javax.swing.tree.DefaultTreeSelectionModel", true),
              })
          .put(
              "NODE_IMPORTED",
              new Import[] {
                new Import("NODE_IMPORTED", "org.w3c.dom.UserDataHandler", true),
              })
          .put(
              "DIALOG_TITLE_CHANGED_PROPERTY",
              new Import[] {
                new Import("DIALOG_TITLE_CHANGED_PROPERTY", "javax.swing.JFileChooser", true),
              })
          .put(
              "NamingContextExt",
              new Import[] {
                new Import("NamingContextExt", "org.omg.CosNaming", false),
              })
          .put(
              "DoubleToLongFunction",
              new Import[] {
                new Import("DoubleToLongFunction", "java.util.function", false),
              })
          .put(
              "PagesPerMinute",
              new Import[] {
                new Import("PagesPerMinute", "javax.print.attribute.standard", false),
              })
          .put(
              "DSAKeyPairGenerator",
              new Import[] {
                new Import("DSAKeyPairGenerator", "java.security.interfaces", false),
              })
          .put(
              "LOCSIZ",
              new Import[] {
                new Import("LOCSIZ", "java.util.jar.JarEntry", true),
                new Import("LOCSIZ", "java.util.jar.JarFile", true),
                new Import("LOCSIZ", "java.util.jar.JarInputStream", true),
                new Import("LOCSIZ", "java.util.jar.JarOutputStream", true),
                new Import("LOCSIZ", "java.util.zip.ZipEntry", true),
                new Import("LOCSIZ", "java.util.zip.ZipFile", true),
                new Import("LOCSIZ", "java.util.zip.ZipInputStream", true),
                new Import("LOCSIZ", "java.util.zip.ZipOutputStream", true),
              })
          .put(
              "MULTIPLE",
              new Import[] {
                new Import("MULTIPLE", "javax.swing.text.html.HTML.Attribute", true),
              })
          .put(
              "clearProperty",
              new Import[] {
                new Import("clearProperty", "java.lang.System", true),
              })
          .put(
              "DOCUMENT_POSITION_CONTAINED_BY",
              new Import[] {
                new Import("DOCUMENT_POSITION_CONTAINED_BY", "org.w3c.dom.Node", true),
              })
          .put(
              "RESERVED_ID_MAX",
              new Import[] {
                new Import("RESERVED_ID_MAX", "java.awt.AWTEvent", true),
              })
          .put(
              "SUPERSCRIPTS_AND_SUBSCRIPTS",
              new Import[] {
                new Import("SUPERSCRIPTS_AND_SUBSCRIPTS", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "MalformedLinkException",
              new Import[] {
                new Import("MalformedLinkException", "javax.naming", false),
              })
          .put(
              "getProvider",
              new Import[] {
                new Import("getProvider", "java.security.Security", true),
              })
          .put(
              "OctetSeqHelper",
              new Import[] {
                new Import("OctetSeqHelper", "org.omg.CORBA", false),
              })
          .put(
              "activeCaptionBorder",
              new Import[] {
                new Import("activeCaptionBorder", "java.awt.SystemColor", true),
              })
          .put(
              "createGroup",
              new Import[] {
                new Import("createGroup", "java.rmi.activation.ActivationGroup", true),
              })
          .put(
              "SQLRecoverableException",
              new Import[] {
                new Import("SQLRecoverableException", "java.sql", false),
              })
          .put(
              "PRIVATE_MEMBER",
              new Import[] {
                new Import("PRIVATE_MEMBER", "org.omg.CORBA", false),
              })
          .put(
              "getDefaultToolkit",
              new Import[] {
                new Import("getDefaultToolkit", "java.awt.Toolkit", true),
              })
          .put(
              "probeContentType",
              new Import[] {
                new Import("probeContentType", "java.nio.file.Files", true),
              })
          .put(
              "InvalidValueHelper",
              new Import[] {
                new Import("InvalidValueHelper", "org.omg.DynamicAny.DynAnyPackage", false),
              })
          .put(
              "format",
              new Import[] {
                new Import("format", "java.lang.String", true),
                new Import("format", "java.text.MessageFormat", true),
              })
          .put(
              "X509EncodedKeySpec",
              new Import[] {
                new Import("X509EncodedKeySpec", "java.security.spec", false),
              })
          .put(
              "InvalidOpenTypeException",
              new Import[] {
                new Import("InvalidOpenTypeException", "javax.management.openmbean", false),
              })
          .put(
              "ProcessingEnvironment",
              new Import[] {
                new Import("ProcessingEnvironment", "javax.annotation.processing", false),
              })
          .put(
              "setLong",
              new Import[] {
                new Import("setLong", "java.lang.reflect.Array", true),
              })
          .put(
              "ENCLOSING_MARK",
              new Import[] {
                new Import("ENCLOSING_MARK", "java.lang.Character", true),
              })
          .put(
              "AlreadyBoundException",
              new Import[] {
                new Import("AlreadyBoundException", "java.nio.channels", false),
                new Import("AlreadyBoundException", "java.rmi", false),
              })
          .put(
              "LOCSIG",
              new Import[] {
                new Import("LOCSIG", "java.util.jar.JarEntry", true),
                new Import("LOCSIG", "java.util.jar.JarFile", true),
                new Import("LOCSIG", "java.util.jar.JarInputStream", true),
                new Import("LOCSIG", "java.util.jar.JarOutputStream", true),
                new Import("LOCSIG", "java.util.zip.ZipEntry", true),
                new Import("LOCSIG", "java.util.zip.ZipFile", true),
                new Import("LOCSIG", "java.util.zip.ZipInputStream", true),
                new Import("LOCSIG", "java.util.zip.ZipOutputStream", true),
              })
          .put(
              "METHOD",
              new Import[] {
                new Import("METHOD", "javax.swing.text.html.HTML.Attribute", true),
                new Import("METHOD", "javax.xml.transform.OutputKeys", true),
              })
          .put(
              "MemoryManagerMXBean",
              new Import[] {
                new Import("MemoryManagerMXBean", "java.lang.management", false),
              })
          .put(
              "URLDecoder",
              new Import[] {
                new Import("URLDecoder", "java.net", false),
              })
          .put(
              "TABLE_HEADER",
              new Import[] {
                new Import("TABLE_HEADER", "javax.swing.plaf.synth.Region", true),
              })
          .put(
              "YELLOW",
              new Import[] {
                new Import("YELLOW", "java.awt.Color", true),
              })
          .put(
              "NullType",
              new Import[] {
                new Import("NullType", "javax.lang.model.type", false),
              })
          .put(
              "WrongPolicyHelper",
              new Import[] {
                new Import("WrongPolicyHelper", "org.omg.PortableServer.POAPackage", false),
              })
          .put(
              "WEIGHT_DEMILIGHT",
              new Import[] {
                new Import("WEIGHT_DEMILIGHT", "java.awt.font.TextAttribute", true),
              })
          .put(
              "getSecurityContext",
              new Import[] {
                new Import("getSecurityContext", "java.rmi.server.RMIClassLoader", true),
              })
          .put(
              "PortUnreachableException",
              new Import[] {
                new Import("PortUnreachableException", "java.net", false),
              })
          .put(
              "LAST_DIVIDER_LOCATION_PROPERTY",
              new Import[] {
                new Import("LAST_DIVIDER_LOCATION_PROPERTY", "javax.swing.JSplitPane", true),
              })
          .put(
              "CopyOnWriteArraySet",
              new Import[] {
                new Import("CopyOnWriteArraySet", "java.util.concurrent", false),
              })
          .put(
              "ValueMemberHelper",
              new Import[] {
                new Import("ValueMemberHelper", "org.omg.CORBA", false),
              })
          .put(
              "X509ExtendedKeyManager",
              new Import[] {
                new Import("X509ExtendedKeyManager", "javax.net.ssl", false),
              })
          .put(
              "RenderingHints",
              new Import[] {
                new Import("RenderingHints", "java.awt", false),
              })
          .put(
              "createMBeanServer",
              new Import[] {
                new Import("createMBeanServer", "javax.management.MBeanServerFactory", true),
              })
          .put(
              "AdditionalComments",
              new Import[] {
                new Import("AdditionalComments", "javax.swing.text.html.HTMLDocument", true),
              })
          .put(
              "PortInfo",
              new Import[] {
                new Import("PortInfo", "javax.xml.ws.handler", false),
              })
          .put(
              "SW_RESIZE_CURSOR",
              new Import[] {
                new Import("SW_RESIZE_CURSOR", "java.awt.Cursor", true),
                new Import("SW_RESIZE_CURSOR", "java.awt.Frame", true),
              })
          .put(
              "OBJ_ADAPTER",
              new Import[] {
                new Import("OBJ_ADAPTER", "org.omg.CORBA", false),
              })
          .put(
              "getImageReadersBySuffix",
              new Import[] {
                new Import("getImageReadersBySuffix", "javax.imageio.ImageIO", true),
              })
          .put(
              "dk_Union",
              new Import[] {
                new Import("dk_Union", "org.omg.CORBA.DefinitionKind", true),
              })
          .put(
              "lowestOneBit",
              new Import[] {
                new Import("lowestOneBit", "java.lang.Integer", true),
                new Import("lowestOneBit", "java.lang.Long", true),
              })
          .put(
              "MidiDeviceTransmitter",
              new Import[] {
                new Import("MidiDeviceTransmitter", "javax.sound.midi", false),
              })
          .put(
              "LinkRef",
              new Import[] {
                new Import("LinkRef", "javax.naming", false),
              })
          .put(
              "DIRECTORY_PANE",
              new Import[] {
                new Import("DIRECTORY_PANE", "javax.accessibility.AccessibleRole", true),
              })
          .put(
              "getInternalFrameMinimizeIcon",
              new Import[] {
                new Import(
                    "getInternalFrameMinimizeIcon",
                    "javax.swing.plaf.metal.MetalIconFactory",
                    true),
              })
          .put(
              "DNS_URL",
              new Import[] {
                new Import("DNS_URL", "javax.naming.Context", true),
              })
          .put(
              "deleteIfExists",
              new Import[] {
                new Import("deleteIfExists", "java.nio.file.Files", true),
              })
          .put(
              "VK_INSERT",
              new Import[] {
                new Import("VK_INSERT", "java.awt.event.KeyEvent", true),
              })
          .put(
              "PROGRAM_CHANGE",
              new Import[] {
                new Import("PROGRAM_CHANGE", "javax.sound.midi.ShortMessage", true),
              })
          .put(
              "SortResponseControl",
              new Import[] {
                new Import("SortResponseControl", "javax.naming.ldap", false),
              })
          .put(
              "FileHandler",
              new Import[] {
                new Import("FileHandler", "java.util.logging", false),
              })
          .put(
              "VK_ALT",
              new Import[] {
                new Import("VK_ALT", "java.awt.event.KeyEvent", true),
              })
          .put(
              "GMONTH",
              new Import[] {
                new Import("GMONTH", "javax.xml.datatype.DatatypeConstants", true),
              })
          .put(
              "PRIORITY_INTERCHAR",
              new Import[] {
                new Import("PRIORITY_INTERCHAR", "java.awt.font.GlyphJustificationInfo", true),
              })
          .put(
              "TEN",
              new Import[] {
                new Import("TEN", "java.math.BigDecimal", true),
                new Import("TEN", "java.math.BigInteger", true),
              })
          .put(
              "BAD_MECH",
              new Import[] {
                new Import("BAD_MECH", "org.ietf.jgss.GSSException", true),
              })
          .put(
              "ClientInfoStatus",
              new Import[] {
                new Import("ClientInfoStatus", "java.sql", false),
              })
          .put(
              "BasicMenuBarUI",
              new Import[] {
                new Import("BasicMenuBarUI", "javax.swing.plaf.basic", false),
              })
          .build();
}
