// Code generated by GenerateStdlib.java. DO NOT EDIT.
package com.nikodoko.javaimports.stdlib.internal.api.v8;

import com.google.common.collect.ImmutableMap;
import com.nikodoko.javaimports.parser.Import;
import java.util.Map;

public class Java8StdlibChunk3 {
  static final Map<String, Import[]> CLASSES =
      new ImmutableMap.Builder<String, Import[]>()
          .put(
              "SOAP_1_2_PROTOCOL",
              new Import[] {
                new Import("SOAP_1_2_PROTOCOL", "javax.xml.soap.SOAPConstants", true),
              })
          .put(
              "DocumentListener",
              new Import[] {
                new Import("DocumentListener", "javax.swing.event", false),
              })
          .put(
              "FieldNameHelper",
              new Import[] {
                new Import("FieldNameHelper", "org.omg.CORBA", false),
                new Import("FieldNameHelper", "org.omg.DynamicAny", false),
              })
          .put(
              "AttributeList",
              new Import[] {
                new Import("AttributeList", "javax.management", false),
                new Import("AttributeList", "javax.swing.text.html.parser", false),
                new Import("AttributeList", "org.xml.sax", false),
              })
          .put(
              "PolicyFactoryOperations",
              new Import[] {
                new Import("PolicyFactoryOperations", "org.omg.PortableInterceptor", false),
              })
          .put(
              "UncheckedIOException",
              new Import[] {
                new Import("UncheckedIOException", "java.io", false),
              })
          .put(
              "MAX_VALUE_FIELD",
              new Import[] {
                new Import("MAX_VALUE_FIELD", "javax.management.JMX", true),
              })
          .put(
              "ITEM_FIRST",
              new Import[] {
                new Import("ITEM_FIRST", "java.awt.event.ItemEvent", true),
              })
          .put(
              "DFN",
              new Import[] {
                new Import("DFN", "javax.swing.text.html.HTML.Tag", true),
              })
          .put(
              "A0",
              new Import[] {
                new Import("A0", "java.awt.PageAttributes.MediaType", true),
                new Import("A0", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "A1",
              new Import[] {
                new Import("A1", "java.awt.PageAttributes.MediaType", true),
                new Import("A1", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "beforeOffset",
              new Import[] {
                new Import("beforeOffset", "java.awt.font.TextHitInfo", true),
              })
          .put(
              "A2",
              new Import[] {
                new Import("A2", "java.awt.PageAttributes.MediaType", true),
                new Import("A2", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "A3",
              new Import[] {
                new Import("A3", "java.awt.PageAttributes.MediaType", true),
                new Import("A3", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "A4",
              new Import[] {
                new Import("A4", "java.awt.PageAttributes.MediaType", true),
                new Import("A4", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "UNDERLINE_LOW_DASHED",
              new Import[] {
                new Import("UNDERLINE_LOW_DASHED", "java.awt.font.TextAttribute", true),
              })
          .put(
              "REMOVAL",
              new Import[] {
                new Import("REMOVAL", "org.w3c.dom.events.MutationEvent", true),
              })
          .put(
              "A5",
              new Import[] {
                new Import("A5", "java.awt.PageAttributes.MediaType", true),
                new Import("A5", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "A6",
              new Import[] {
                new Import("A6", "java.awt.PageAttributes.MediaType", true),
                new Import("A6", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "PrintQualityType",
              new Import[] {
                new Import("PrintQualityType", "java.awt.PageAttributes", false),
              })
          .put(
              "A7",
              new Import[] {
                new Import("A7", "java.awt.PageAttributes.MediaType", true),
                new Import("A7", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "SCROLLBARS_NONE",
              new Import[] {
                new Import("SCROLLBARS_NONE", "java.awt.TextArea", true),
              })
          .put(
              "A8",
              new Import[] {
                new Import("A8", "java.awt.PageAttributes.MediaType", true),
                new Import("A8", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "A9",
              new Import[] {
                new Import("A9", "java.awt.PageAttributes.MediaType", true),
                new Import("A9", "javax.print.attribute.standard.MediaSize.ISO", true),
              })
          .put(
              "JobState",
              new Import[] {
                new Import("JobState", "javax.print.attribute.standard", false),
              })
          .put(
              "AudioFormat",
              new Import[] {
                new Import("AudioFormat", "javax.sound.sampled", false),
              })
          .put(
              "MethodHandleInfo",
              new Import[] {
                new Import("MethodHandleInfo", "java.lang.invoke", false),
              })
          .put(
              "JOB_FAILED",
              new Import[] {
                new Import("JOB_FAILED", "javax.print.event.PrintJobEvent", true),
              })
          .put(
              "DGC",
              new Import[] {
                new Import("DGC", "java.rmi.dgc", false),
              })
          .put(
              "AD",
              new Import[] {
                new Import("AD", "java.util.GregorianCalendar", true),
              })
          .put(
              "AbstractButton",
              new Import[] {
                new Import("AbstractButton", "javax.swing", false),
              })
          .put(
              "BasicEditorPaneUI",
              new Import[] {
                new Import("BasicEditorPaneUI", "javax.swing.plaf.basic", false),
              })
          .put(
              "OptionPaneUI",
              new Import[] {
                new Import("OptionPaneUI", "javax.swing.plaf", false),
              })
          .put(
              "KEY_STROKE_CONTROL",
              new Import[] {
                new Import("KEY_STROKE_CONTROL", "java.awt.RenderingHints", true),
              })
          .put(
              "isEventDispatchThread",
              new Import[] {
                new Import("isEventDispatchThread", "javax.swing.SwingUtilities", true),
              })
          .put(
              "doLookup",
              new Import[] {
                new Import("doLookup", "javax.naming.InitialContext", true),
              })
          .put(
              "AM",
              new Import[] {
                new Import("AM", "java.util.Calendar", true),
              })
          .put(
              "DEFAULT_CARET_POLICY",
              new Import[] {
                new Import("DEFAULT_CARET_POLICY", "java.awt.font.TextLayout", true),
              })
          .put(
              "B0",
              new Import[] {
                new Import("B0", "java.awt.PageAttributes.MediaType", true),
                new Import("B0", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B0", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "B1",
              new Import[] {
                new Import("B1", "java.awt.PageAttributes.MediaType", true),
                new Import("B1", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B1", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "IDENTITY",
              new Import[] {
                new Import("IDENTITY", "java.awt.font.TransformAttribute", true),
              })
          .put(
              "B2",
              new Import[] {
                new Import("B2", "java.awt.PageAttributes.MediaType", true),
                new Import("B2", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B2", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "ofSecondOfDay",
              new Import[] {
                new Import("ofSecondOfDay", "java.time.LocalTime", true),
              })
          .put(
              "B3",
              new Import[] {
                new Import("B3", "java.awt.PageAttributes.MediaType", true),
                new Import("B3", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B3", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "UID",
              new Import[] {
                new Import("UID", "java.rmi.server", false),
              })
          .put(
              "ComboPopup",
              new Import[] {
                new Import("ComboPopup", "javax.swing.plaf.basic", false),
              })
          .put(
              "B4",
              new Import[] {
                new Import("B4", "java.awt.PageAttributes.MediaType", true),
                new Import("B4", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B4", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "B5",
              new Import[] {
                new Import("B5", "java.awt.PageAttributes.MediaType", true),
                new Import("B5", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B5", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "MultiTextUI",
              new Import[] {
                new Import("MultiTextUI", "javax.swing.plaf.multi", false),
              })
          .put(
              "B6",
              new Import[] {
                new Import("B6", "java.awt.PageAttributes.MediaType", true),
                new Import("B6", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B6", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "AU",
              new Import[] {
                new Import("AU", "javax.sound.sampled.AudioFileFormat.Type", true),
              })
          .put(
              "DELEGATE_NAME",
              new Import[] {
                new Import("DELEGATE_NAME", "javax.management.MBeanServerDelegate", true),
              })
          .put(
              "JPasswordField",
              new Import[] {
                new Import("JPasswordField", "javax.swing", false),
              })
          .put(
              "B7",
              new Import[] {
                new Import("B7", "java.awt.PageAttributes.MediaType", true),
                new Import("B7", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B7", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "PRIVATE_USE_AREA",
              new Import[] {
                new Import("PRIVATE_USE_AREA", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "B8",
              new Import[] {
                new Import("B8", "java.awt.PageAttributes.MediaType", true),
                new Import("B8", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B8", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "B9",
              new Import[] {
                new Import("B9", "java.awt.PageAttributes.MediaType", true),
                new Import("B9", "javax.print.attribute.standard.MediaSize.ISO", true),
                new Import("B9", "javax.print.attribute.standard.MediaSize.JIS", true),
              })
          .put(
              "isRightMouseButton",
              new Import[] {
                new Import("isRightMouseButton", "javax.swing.SwingUtilities", true),
              })
          .put(
              "Readable",
              new Import[] {
                new Import("Readable", "java.lang", false),
              })
          .put(
              "HttpCookie",
              new Import[] {
                new Import("HttpCookie", "java.net", false),
              })
          .put(
              "isReadable",
              new Import[] {
                new Import("isReadable", "java.nio.file.Files", true),
              })
          .put(
              "BadBinaryOpValueExpException",
              new Import[] {
                new Import("BadBinaryOpValueExpException", "javax.management", false),
              })
          .put(
              "getTreeControlIcon",
              new Import[] {
                new Import("getTreeControlIcon", "javax.swing.plaf.metal.MetalIconFactory", true),
              })
          .put(
              "GENERAL_PUNCTUATION",
              new Import[] {
                new Import("GENERAL_PUNCTUATION", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "BeanContextServicesListener",
              new Import[] {
                new Import("BeanContextServicesListener", "java.beans.beancontext", false),
              })
          .put(
              "JAXBPermission",
              new Import[] {
                new Import("JAXBPermission", "javax.xml.bind", false),
              })
          .put(
              "PolicyHolder",
              new Import[] {
                new Import("PolicyHolder", "org.omg.CORBA", false),
              })
          .put(
              "BasicArrowButton",
              new Import[] {
                new Import("BasicArrowButton", "javax.swing.plaf.basic", false),
              })
          .put(
              "tk_ushort",
              new Import[] {
                new Import("tk_ushort", "org.omg.CORBA.TCKind", true),
              })
          .put(
              "DirectColorModel",
              new Import[] {
                new Import("DirectColorModel", "java.awt.image", false),
              })
          .put(
              "RAISED",
              new Import[] {
                new Import("RAISED", "javax.swing.border.BevelBorder", true),
                new Import("RAISED", "javax.swing.border.EtchedBorder", true),
              })
          .put(
              "ConcurrentNavigableMap",
              new Import[] {
                new Import("ConcurrentNavigableMap", "java.util.concurrent", false),
              })
          .put(
              "selectBestTextFlavor",
              new Import[] {
                new Import("selectBestTextFlavor", "java.awt.datatransfer.DataFlavor", true),
              })
          .put(
              "REF_MBEAN_NOT_REGISTERED",
              new Import[] {
                new Import(
                    "REF_MBEAN_NOT_REGISTERED", "javax.management.relation.RoleStatus", true),
              })
          .put(
              "DecimalFormatSymbols",
              new Import[] {
                new Import("DecimalFormatSymbols", "java.text", false),
              })
          .put(
              "getProxyClass",
              new Import[] {
                new Import("getProxyClass", "java.lang.reflect.Proxy", true),
              })
          .put(
              "NamingEvent",
              new Import[] {
                new Import("NamingEvent", "javax.naming.event", false),
              })
          .put(
              "getInternalFrameDefaultMenuIcon",
              new Import[] {
                new Import(
                    "getInternalFrameDefaultMenuIcon",
                    "javax.swing.plaf.metal.MetalIconFactory",
                    true),
              })
          .put(
              "icSigLuvData",
              new Import[] {
                new Import("icSigLuvData", "java.awt.color.ICC_Profile", true),
              })
          .put(
              "icSigBToA1Tag",
              new Import[] {
                new Import("icSigBToA1Tag", "java.awt.color.ICC_Profile", true),
              })
          .put(
              "RuntimeMXBean",
              new Import[] {
                new Import("RuntimeMXBean", "java.lang.management", false),
              })
          .put(
              "FormatStyle",
              new Import[] {
                new Import("FormatStyle", "java.time.format", false),
              })
          .put(
              "MemoryUsage",
              new Import[] {
                new Import("MemoryUsage", "java.lang.management", false),
              })
          .put(
              "SerializedLambda",
              new Import[] {
                new Import("SerializedLambda", "java.lang.invoke", false),
              })
          .put(
              "FOREGROUND",
              new Import[] {
                new Import("FOREGROUND", "java.awt.font.TextAttribute", true),
                new Import("FOREGROUND", "javax.swing.plaf.synth.ColorType", true),
              })
          .put(
              "FONT_CHANGE_BIGGER",
              new Import[] {
                new Import("FONT_CHANGE_BIGGER", "javax.swing.text.html.HTMLEditorKit", true),
              })
          .put(
              "UTFDataFormatException",
              new Import[] {
                new Import("UTFDataFormatException", "java.io", false),
              })
          .put(
              "ALLBITS",
              new Import[] {
                new Import("ALLBITS", "java.awt.image.ImageObserver", true),
              })
          .put(
              "CompletionException",
              new Import[] {
                new Import("CompletionException", "java.util.concurrent", false),
              })
          .put(
              "Event",
              new Import[] {
                new Import("Event", "java.awt", false),
                new Import("Event", "org.w3c.dom.events", false),
              })
          .put(
              "STRING",
              new Import[] {
                new Import("STRING", "javax.management.openmbean.SimpleType", true),
                new Import("STRING", "javax.print.DocFlavor", false),
                new Import("STRING", "javax.xml.xpath.XPathConstants", true),
              })
          .put(
              "getDefaultHostnameVerifier",
              new Import[] {
                new Import("getDefaultHostnameVerifier", "javax.net.ssl.HttpsURLConnection", true),
              })
          .put(
              "TEXT_HTML",
              new Import[] {
                new Import("TEXT_HTML", "javax.print.DocFlavor.CHAR_ARRAY", true),
                new Import("TEXT_HTML", "javax.print.DocFlavor.READER", true),
                new Import("TEXT_HTML", "javax.print.DocFlavor.STRING", true),
              })
          .put(
              "SimpleJavaFileObject",
              new Import[] {
                new Import("SimpleJavaFileObject", "javax.tools", false),
              })
          .put(
              "REF_CURSOR",
              new Import[] {
                new Import("REF_CURSOR", "java.sql.Types", true),
              })
          .put(
              "QUARTER_OF_YEAR",
              new Import[] {
                new Import("QUARTER_OF_YEAR", "java.time.temporal.IsoFields", true),
              })
          .put(
              "tickMinutes",
              new Import[] {
                new Import("tickMinutes", "java.time.Clock", true),
              })
          .put(
              "TMNOFLAGS",
              new Import[] {
                new Import("TMNOFLAGS", "javax.transaction.xa.XAResource", true),
              })
          .put(
              "DOWN_CYCLE_TRAVERSAL_KEYS",
              new Import[] {
                new Import("DOWN_CYCLE_TRAVERSAL_KEYS", "java.awt.KeyboardFocusManager", true),
              })
          .put(
              "TYPE_NEAREST_NEIGHBOR",
              new Import[] {
                new Import("TYPE_NEAREST_NEIGHBOR", "java.awt.image.AffineTransformOp", true),
              })
          .put(
              "JAXBSource",
              new Import[] {
                new Import("JAXBSource", "javax.xml.bind.util", false),
              })
          .put(
              "PrintRequestAttributeSet",
              new Import[] {
                new Import("PrintRequestAttributeSet", "javax.print.attribute", false),
              })
          .put(
              "UNSPECIFIED_EVENT_TYPE_ERR",
              new Import[] {
                new Import("UNSPECIFIED_EVENT_TYPE_ERR", "org.w3c.dom.events.EventException", true),
              })
          .put(
              "unexportObject",
              new Import[] {
                new Import("unexportObject", "java.rmi.activation.Activatable", true),
                new Import("unexportObject", "java.rmi.server.UnicastRemoteObject", true),
                new Import("unexportObject", "javax.rmi.PortableRemoteObject", true),
                new Import("unexportObject", "javax.rmi.CORBA.Util", true),
              })
          .put(
              "FIELD_COUNT",
              new Import[] {
                new Import("FIELD_COUNT", "java.util.Calendar", true),
              })
          .put(
              "SEVERITY_WARNING",
              new Import[] {
                new Import("SEVERITY_WARNING", "org.w3c.dom.DOMError", true),
              })
          .put(
              "ENTITIES",
              new Import[] {
                new Import("ENTITIES", "javax.swing.text.html.parser.DTDConstants", true),
              })
          .put(
              "WeekFields",
              new Import[] {
                new Import("WeekFields", "java.time.temporal", false),
              })
          .put(
              "getMixer",
              new Import[] {
                new Import("getMixer", "javax.sound.sampled.AudioSystem", true),
              })
          .put(
              "TextComponent",
              new Import[] {
                new Import("TextComponent", "java.awt", false),
              })
          .put(
              "RETURN_GENERATED_KEYS",
              new Import[] {
                new Import("RETURN_GENERATED_KEYS", "java.sql.Statement", true),
              })
          .put(
              "MalformedObjectNameException",
              new Import[] {
                new Import("MalformedObjectNameException", "javax.management", false),
              })
          .put(
              "NUMBER",
              new Import[] {
                new Import("NUMBER", "javax.swing.text.html.parser.DTDConstants", true),
                new Import("NUMBER", "javax.xml.xpath.XPathConstants", true),
              })
          .put(
              "PrivilegedActionException",
              new Import[] {
                new Import("PrivilegedActionException", "java.security", false),
              })
          .put(
              "TUESDAY",
              new Import[] {
                new Import("TUESDAY", "java.util.Calendar", true),
              })
          .put(
              "PresentationDirection",
              new Import[] {
                new Import("PresentationDirection", "javax.print.attribute.standard", false),
              })
          .put(
              "MOUSE_DOWN",
              new Import[] {
                new Import("MOUSE_DOWN", "java.awt.Event", true),
              })
          .put(
              "ByteLookupTable",
              new Import[] {
                new Import("ByteLookupTable", "java.awt.image", false),
              })
          .put(
              "NoSuchMethodError",
              new Import[] {
                new Import("NoSuchMethodError", "java.lang", false),
              })
          .put(
              "MBeanServerForwarder",
              new Import[] {
                new Import("MBeanServerForwarder", "javax.management.remote", false),
              })
          .put(
              "getDateTimeInstance",
              new Import[] {
                new Import("getDateTimeInstance", "java.text.DateFormat", true),
              })
          .put(
              "EventListenerProxy",
              new Import[] {
                new Import("EventListenerProxy", "java.util", false),
              })
          .put(
              "getLookAndFeelDefaults",
              new Import[] {
                new Import("getLookAndFeelDefaults", "javax.swing.UIManager", true),
              })
          .put(
              "MEETEI_MAYEK",
              new Import[] {
                new Import("MEETEI_MAYEK", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "ECPublicKey",
              new Import[] {
                new Import("ECPublicKey", "java.security.interfaces", false),
              })
          .put(
              "RUNTIME_ERROR",
              new Import[] {
                new Import("RUNTIME_ERROR", "javax.management.monitor.MonitorNotification", true),
              })
          .put(
              "LIGATURES",
              new Import[] {
                new Import("LIGATURES", "java.awt.font.TextAttribute", true),
              })
          .put(
              "BeanContextServiceRevokedListener",
              new Import[] {
                new Import("BeanContextServiceRevokedListener", "java.beans.beancontext", false),
              })
          .put(
              "AsyncHandler",
              new Import[] {
                new Import("AsyncHandler", "javax.xml.ws", false),
              })
          .put(
              "getKeyText",
              new Import[] {
                new Import("getKeyText", "java.awt.event.KeyEvent", true),
              })
          .put(
              "REF_putField",
              new Import[] {
                new Import("REF_putField", "java.lang.invoke.MethodHandleInfo", true),
              })
          .put(
              "Time",
              new Import[] {
                new Import("Time", "java.sql", false),
              })
          .put(
              "HTTP_VERSION",
              new Import[] {
                new Import("HTTP_VERSION", "java.net.HttpURLConnection", true),
              })
          .put(
              "SPIN_BOX",
              new Import[] {
                new Import("SPIN_BOX", "javax.accessibility.AccessibleRole", true),
              })
          .put(
              "NameDynAnyPairHelper",
              new Import[] {
                new Import("NameDynAnyPairHelper", "org.omg.DynamicAny", false),
              })
          .put(
              "showDialog",
              new Import[] {
                new Import("showDialog", "javax.swing.JColorChooser", true),
              })
          .put(
              "DeflaterOutputStream",
              new Import[] {
                new Import("DeflaterOutputStream", "java.util.zip", false),
              })
          .put(
              "PASSWORD_PROPERTY",
              new Import[] {
                new Import("PASSWORD_PROPERTY", "javax.xml.ws.BindingProvider", true),
              })
          .put(
              "UncaughtExceptionHandler",
              new Import[] {
                new Import("UncaughtExceptionHandler", "java.lang.Thread", false),
              })
          .put(
              "publicLookup",
              new Import[] {
                new Import("publicLookup", "java.lang.invoke.MethodHandles", true),
              })
          .put(
              "ThreadPolicyOperations",
              new Import[] {
                new Import("ThreadPolicyOperations", "org.omg.PortableServer", false),
              })
          .put(
              "primaryOrder",
              new Import[] {
                new Import("primaryOrder", "java.text.CollationElementIterator", true),
              })
          .put(
              "CHILD_POLICY_EMPTY",
              new Import[] {
                new Import("CHILD_POLICY_EMPTY", "javax.imageio.metadata.IIOMetadataFormat", true),
              })
          .put(
              "IntPredicate",
              new Import[] {
                new Import("IntPredicate", "java.util.function", false),
              })
          .put(
              "FileImageOutputStream",
              new Import[] {
                new Import("FileImageOutputStream", "javax.imageio.stream", false),
              })
          .put(
              "TextSyntax",
              new Import[] {
                new Import("TextSyntax", "javax.print.attribute", false),
              })
          .put(
              "JavaCompiler",
              new Import[] {
                new Import("JavaCompiler", "javax.tools", false),
              })
          .put(
              "Flush3DBorder",
              new Import[] {
                new Import("Flush3DBorder", "javax.swing.plaf.metal.MetalBorders", false),
              })
          .put(
              "_COMPLETED_YES",
              new Import[] {
                new Import("_COMPLETED_YES", "org.omg.CORBA.CompletionStatus", true),
              })
          .put(
              "ByteArrayOutputStream",
              new Import[] {
                new Import("ByteArrayOutputStream", "java.io", false),
              })
          .put(
              "REPORT",
              new Import[] {
                new Import("REPORT", "java.nio.charset.CodingErrorAction", true),
                new Import("REPORT", "javax.print.attribute.standard.Severity", true),
              })
          .put(
              "setComponent",
              new Import[] {
                new Import("setComponent", "javax.swing.text.StyleConstants", true),
              })
          .put(
              "LATEST",
              new Import[] {
                new Import("LATEST", "java.util.jar.Pack200.Packer", true),
              })
          .put(
              "CannotProceed",
              new Import[] {
                new Import("CannotProceed", "org.omg.CosNaming.NamingContextPackage", false),
              })
          .put(
              "TAG_NAME",
              new Import[] {
                new Import("TAG_NAME", "java.awt.font.OpenType", true),
              })
          .put(
              "MODAL",
              new Import[] {
                new Import("MODAL", "javax.accessibility.AccessibleState", true),
              })
          .put(
              "RepaintManager",
              new Import[] {
                new Import("RepaintManager", "javax.swing", false),
              })
          .put(
              "IllegalThreadStateException",
              new Import[] {
                new Import("IllegalThreadStateException", "java.lang", false),
              })
          .put(
              "RequestProcessingPolicyOperations",
              new Import[] {
                new Import("RequestProcessingPolicyOperations", "org.omg.PortableServer", false),
              })
          .put(
              "selectParagraphAction",
              new Import[] {
                new Import("selectParagraphAction", "javax.swing.text.DefaultEditorKit", true),
              })
          .put(
              "SOAPFault",
              new Import[] {
                new Import("SOAPFault", "javax.xml.soap", false),
              })
          .put(
              "TEXT_TEXT",
              new Import[] {
                new Import("TEXT_TEXT", "java.awt.SystemColor", true),
              })
          .put(
              "RANDOMPIXELORDER",
              new Import[] {
                new Import("RANDOMPIXELORDER", "java.awt.image.ImageConsumer", true),
              })
          .put(
              "TemporalAccessor",
              new Import[] {
                new Import("TemporalAccessor", "java.time.temporal", false),
              })
          .put(
              "mapEquivalents",
              new Import[] {
                new Import("mapEquivalents", "java.util.Locale.LanguageRange", true),
              })
          .put(
              "WINDOW_ICONIFIED",
              new Import[] {
                new Import("WINDOW_ICONIFIED", "java.awt.event.WindowEvent", true),
              })
          .put(
              "PropertyResourceBundle",
              new Import[] {
                new Import("PropertyResourceBundle", "java.util", false),
              })
          .put(
              "MOUSE_UP",
              new Import[] {
                new Import("MOUSE_UP", "java.awt.Event", true),
              })
          .put(
              "TABLE",
              new Import[] {
                new Import("TABLE", "javax.accessibility.AccessibleRole", true),
                new Import("TABLE", "javax.swing.plaf.synth.Region", true),
                new Import("TABLE", "javax.swing.text.html.HTML.Tag", true),
              })
          .put(
              "DERIVATION_UNION",
              new Import[] {
                new Import("DERIVATION_UNION", "org.w3c.dom.TypeInfo", true),
              })
          .put(
              "floatToIntBits",
              new Import[] {
                new Import("floatToIntBits", "java.lang.Float", true),
              })
          .put(
              "finalSubString",
              new Import[] {
                new Import("finalSubString", "javax.management.Query", true),
              })
          .put(
              "getDTD",
              new Import[] {
                new Import("getDTD", "javax.swing.text.html.parser.DTD", true),
              })
          .put(
              "MarginBorder",
              new Import[] {
                new Import("MarginBorder", "javax.swing.plaf.basic.BasicBorders", false),
              })
          .put(
              "addAuxiliaryLookAndFeel",
              new Import[] {
                new Import("addAuxiliaryLookAndFeel", "javax.swing.UIManager", true),
              })
          .put(
              "SAXParser",
              new Import[] {
                new Import("SAXParser", "javax.xml.parsers", false),
              })
          .put(
              "TYPE",
              new Import[] {
                new Import("TYPE", "java.lang.Boolean", true),
                new Import("TYPE", "java.lang.Byte", true),
                new Import("TYPE", "java.lang.Character", true),
                new Import("TYPE", "java.lang.Double", true),
                new Import("TYPE", "java.lang.Float", true),
                new Import("TYPE", "java.lang.Integer", true),
                new Import("TYPE", "java.lang.Long", true),
                new Import("TYPE", "java.lang.Short", true),
                new Import("TYPE", "java.lang.Void", true),
                new Import("TYPE", "javax.swing.text.html.HTML.Attribute", true),
                new Import("TYPE", "javax.xml.crypto.dsig.Manifest", true),
                new Import("TYPE", "javax.xml.crypto.dsig.SignatureProperties", true),
                new Import("TYPE", "javax.xml.crypto.dsig.XMLObject", true),
                new Import("TYPE", "javax.xml.crypto.dsig.keyinfo.PGPData", true),
                new Import("TYPE", "javax.xml.crypto.dsig.keyinfo.X509Data", true),
              })
          .put(
              "ReentrantLock",
              new Import[] {
                new Import("ReentrantLock", "java.util.concurrent.locks", false),
              })
          .put(
              "BasicCheckBoxMenuItemUI",
              new Import[] {
                new Import("BasicCheckBoxMenuItemUI", "javax.swing.plaf.basic", false),
              })
          .put(
              "getWhite",
              new Import[] {
                new Import("getWhite", "javax.swing.plaf.metal.MetalLookAndFeel", true),
              })
          .put(
              "isStrikeThrough",
              new Import[] {
                new Import("isStrikeThrough", "javax.swing.text.StyleConstants", true),
              })
          .put(
              "SUPPORT_DTD",
              new Import[] {
                new Import("SUPPORT_DTD", "javax.xml.stream.XMLInputFactory", true),
              })
          .put(
              "CodeSource",
              new Import[] {
                new Import("CodeSource", "java.security", false),
              })
          .put(
              "TableColumn",
              new Import[] {
                new Import("TableColumn", "javax.swing.table", false),
              })
          .put(
              "_MULTIPLE_ID",
              new Import[] {
                new Import("_MULTIPLE_ID", "org.omg.PortableServer.IdUniquenessPolicyValue", true),
              })
          .put(
              "getByInetAddress",
              new Import[] {
                new Import("getByInetAddress", "java.net.NetworkInterface", true),
              })
          .put(
              "VISIBLE_ROW_COUNT_PROPERTY",
              new Import[] {
                new Import("VISIBLE_ROW_COUNT_PROPERTY", "javax.swing.JTree", true),
              })
          .put(
              "icSigPs2CRD3Tag",
              new Import[] {
                new Import("icSigPs2CRD3Tag", "java.awt.color.ICC_Profile", true),
              })
          .put(
              "setProperty",
              new Import[] {
                new Import("setProperty", "java.lang.System", true),
                new Import("setProperty", "java.security.Security", true),
              })
          .put(
              "MIN_RADIX",
              new Import[] {
                new Import("MIN_RADIX", "java.lang.Character", true),
              })
          .put(
              "STANDBY",
              new Import[] {
                new Import("STANDBY", "javax.swing.text.html.HTML.Attribute", true),
              })
          .put(
              "SchemaFactoryLoader",
              new Import[] {
                new Import("SchemaFactoryLoader", "javax.xml.validation", false),
              })
          .put(
              "AUX_RETURN",
              new Import[] {
                new Import("AUX_RETURN", "javax.sound.sampled.FloatControl.Type", true),
              })
          .put(
              "putDTDHash",
              new Import[] {
                new Import("putDTDHash", "javax.swing.text.html.parser.DTD", true),
              })
          .put(
              "AlgorithmParameterSpec",
              new Import[] {
                new Import("AlgorithmParameterSpec", "java.security.spec", false),
              })
          .put(
              "LayerUI",
              new Import[] {
                new Import("LayerUI", "javax.swing.plaf", false),
              })
          .put(
              "BASELINE_LEADING",
              new Import[] {
                new Import("BASELINE_LEADING", "java.awt.GridBagConstraints", true),
              })
          .put(
              "NotContextException",
              new Import[] {
                new Import("NotContextException", "javax.naming", false),
              })
          .put(
              "naturalOrder",
              new Import[] {
                new Import("naturalOrder", "java.util.Comparator", true),
              })
          .put(
              "SecureCacheResponse",
              new Import[] {
                new Import("SecureCacheResponse", "java.net", false),
              })
          .put(
              "ISO_A4_TRANSPARENT",
              new Import[] {
                new Import("ISO_A4_TRANSPARENT", "javax.print.attribute.standard.MediaName", true),
              })
          .put(
              "ROOT_VISIBLE_PROPERTY",
              new Import[] {
                new Import("ROOT_VISIBLE_PROPERTY", "javax.swing.JTree", true),
              })
          .put(
              "parseBoolean",
              new Import[] {
                new Import("parseBoolean", "java.lang.Boolean", true),
                new Import("parseBoolean", "javax.xml.bind.DatatypeConverter", true),
              })
          .put(
              "COMMENTS",
              new Import[] {
                new Import("COMMENTS", "java.util.regex.Pattern", true),
              })
          .put(
              "TYPE_GENERAL_SCALE",
              new Import[] {
                new Import("TYPE_GENERAL_SCALE", "java.awt.geom.AffineTransform", true),
              })
          .put(
              "ByteOrder",
              new Import[] {
                new Import("ByteOrder", "java.nio", false),
              })
          .put(
              "DataFlavor",
              new Import[] {
                new Import("DataFlavor", "java.awt.datatransfer", false),
              })
          .put(
              "ObjectReferenceTemplateSeqHolder",
              new Import[] {
                new Import(
                    "ObjectReferenceTemplateSeqHolder", "org.omg.PortableInterceptor", false),
              })
          .put(
              "remainderUnsigned",
              new Import[] {
                new Import("remainderUnsigned", "java.lang.Integer", true),
                new Import("remainderUnsigned", "java.lang.Long", true),
              })
          .put(
              "ProviderNotFoundException",
              new Import[] {
                new Import("ProviderNotFoundException", "java.nio.file", false),
              })
          .put(
              "LOWERED",
              new Import[] {
                new Import("LOWERED", "javax.swing.border.BevelBorder", true),
                new Import("LOWERED", "javax.swing.border.EtchedBorder", true),
              })
          .put(
              "getMenuForeground",
              new Import[] {
                new Import("getMenuForeground", "javax.swing.plaf.metal.MetalLookAndFeel", true),
              })
          .put(
              "identity",
              new Import[] {
                new Import("identity", "java.lang.invoke.MethodHandles", true),
                new Import("identity", "java.util.function.DoubleUnaryOperator", true),
                new Import("identity", "java.util.function.Function", true),
                new Import("identity", "java.util.function.IntUnaryOperator", true),
                new Import("identity", "java.util.function.LongUnaryOperator", true),
                new Import("identity", "java.util.function.UnaryOperator", true),
              })
          .put(
              "WINDOW_EVENT_MASK",
              new Import[] {
                new Import("WINDOW_EVENT_MASK", "java.awt.AWTEvent", true),
              })
          .put(
              "SYNTAX_ERR",
              new Import[] {
                new Import("SYNTAX_ERR", "org.w3c.dom.DOMException", true),
              })
          .put(
              "RTFEditorKit",
              new Import[] {
                new Import("RTFEditorKit", "javax.swing.text.rtf", false),
              })
          .put(
              "ImageReader",
              new Import[] {
                new Import("ImageReader", "javax.imageio", false),
              })
          .put(
              "BORDER_WIDTH",
              new Import[] {
                new Import("BORDER_WIDTH", "javax.swing.text.html.CSS.Attribute", true),
              })
          .put(
              "tk_alias",
              new Import[] {
                new Import("tk_alias", "org.omg.CORBA.TCKind", true),
              })
          .put(
              "VALUE_ARBITRARY",
              new Import[] {
                new Import("VALUE_ARBITRARY", "javax.imageio.metadata.IIOMetadataFormat", true),
              })
          .put(
              "DesktopManager",
              new Import[] {
                new Import("DesktopManager", "javax.swing", false),
              })
          .put(
              "LineNumberInputStream",
              new Import[] {
                new Import("LineNumberInputStream", "java.io", false),
              })
          .put(
              "constructorModifiers",
              new Import[] {
                new Import("constructorModifiers", "java.lang.reflect.Modifier", true),
              })
          .put(
              "KeyStoreException",
              new Import[] {
                new Import("KeyStoreException", "java.security", false),
              })
          .put(
              "MODEL",
              new Import[] {
                new Import("MODEL", "javax.swing.text.html.parser.DTDConstants", true),
              })
          .put(
              "getUIActionMap",
              new Import[] {
                new Import("getUIActionMap", "javax.swing.SwingUtilities", true),
              })
          .put(
              "LongToDoubleFunction",
              new Import[] {
                new Import("LongToDoubleFunction", "java.util.function", false),
              })
          .put(
              "Graphics",
              new Import[] {
                new Import("Graphics", "java.awt", false),
              })
          .put(
              "IllegalChannelGroupException",
              new Import[] {
                new Import("IllegalChannelGroupException", "java.nio.channels", false),
              })
          .put(
              "STREAM_MAGIC",
              new Import[] {
                new Import("STREAM_MAGIC", "java.io.ObjectStreamConstants", true),
              })
          .put(
              "EllipticCurve",
              new Import[] {
                new Import("EllipticCurve", "java.security.spec", false),
              })
          .put(
              "exists",
              new Import[] {
                new Import("exists", "java.nio.file.Files", true),
              })
          .put(
              "Tag",
              new Import[] {
                new Import("Tag", "javax.swing.text.html.HTML", false),
              })
          .put(
              "INPUT_METHOD_FIRST",
              new Import[] {
                new Import("INPUT_METHOD_FIRST", "java.awt.event.InputMethodEvent", true),
              })
          .put(
              "createSoftBevelBorder",
              new Import[] {
                new Import("createSoftBevelBorder", "javax.swing.BorderFactory", true),
              })
          .put(
              "MEMBER_OF",
              new Import[] {
                new Import("MEMBER_OF", "javax.accessibility.AccessibleRelation", true),
              })
          .put(
              "Characters",
              new Import[] {
                new Import("Characters", "javax.xml.stream.events", false),
              })
          .put(
              "EXTHDR",
              new Import[] {
                new Import("EXTHDR", "java.util.jar.JarEntry", true),
                new Import("EXTHDR", "java.util.jar.JarFile", true),
                new Import("EXTHDR", "java.util.jar.JarInputStream", true),
                new Import("EXTHDR", "java.util.jar.JarOutputStream", true),
                new Import("EXTHDR", "java.util.zip.ZipEntry", true),
                new Import("EXTHDR", "java.util.zip.ZipFile", true),
                new Import("EXTHDR", "java.util.zip.ZipInputStream", true),
                new Import("EXTHDR", "java.util.zip.ZipOutputStream", true),
              })
          .put(
              "TabStop",
              new Import[] {
                new Import("TabStop", "javax.swing.text", false),
              })
          .put(
              "Cursor",
              new Import[] {
                new Import("Cursor", "java.awt", false),
              })
          .put(
              "LinkedHashMap",
              new Import[] {
                new Import("LinkedHashMap", "java.util", false),
              })
          .put(
              "loadKeymap",
              new Import[] {
                new Import("loadKeymap", "javax.swing.text.JTextComponent", true),
              })
          .put(
              "getISOCountries",
              new Import[] {
                new Import("getISOCountries", "java.util.Locale", true),
              })
          .put(
              "icHdrVersion",
              new Import[] {
                new Import("icHdrVersion", "java.awt.color.ICC_Profile", true),
              })
          .put(
              "TextField",
              new Import[] {
                new Import("TextField", "java.awt", false),
              })
          .put(
              "GoodBreakWeight",
              new Import[] {
                new Import("GoodBreakWeight", "javax.swing.text.View", true),
              })
          .put(
              "TYPE_MISMATCH_ERR",
              new Import[] {
                new Import("TYPE_MISMATCH_ERR", "org.w3c.dom.DOMException", true),
              })
          .put(
              "LSOutput",
              new Import[] {
                new Import("LSOutput", "org.w3c.dom.ls", false),
              })
          .put(
              "pageUpAction",
              new Import[] {
                new Import("pageUpAction", "javax.swing.text.DefaultEditorKit", true),
              })
          .put(
              "VK_COMMA",
              new Import[] {
                new Import("VK_COMMA", "java.awt.event.KeyEvent", true),
              })
          .put(
              "HasControls",
              new Import[] {
                new Import("HasControls", "javax.naming.ldap", false),
              })
          .put(
              "PrintJob",
              new Import[] {
                new Import("PrintJob", "java.awt", false),
              })
          .put(
              "Resource",
              new Import[] {
                new Import("Resource", "javax.annotation", false),
              })
          .put(
              "ISO_ZONED_DATE_TIME",
              new Import[] {
                new Import("ISO_ZONED_DATE_TIME", "java.time.format.DateTimeFormatter", true),
              })
          .put(
              "MAX_EXPONENT",
              new Import[] {
                new Import("MAX_EXPONENT", "java.lang.Double", true),
                new Import("MAX_EXPONENT", "java.lang.Float", true),
              })
          .put(
              "NEGATIVE_SCROLL",
              new Import[] {
                new Import("NEGATIVE_SCROLL", "javax.swing.plaf.basic.BasicSliderUI", true),
              })
          .put(
              "StdACLuminance",
              new Import[] {
                new Import("StdACLuminance", "javax.imageio.plugins.jpeg.JPEGHuffmanTable", true),
              })
          .put(
              "SAXResult",
              new Import[] {
                new Import("SAXResult", "javax.xml.transform.sax", false),
              })
          .put(
              "MultiMenuBarUI",
              new Import[] {
                new Import("MultiMenuBarUI", "javax.swing.plaf.multi", false),
              })
          .put(
              "VK_MODECHANGE",
              new Import[] {
                new Import("VK_MODECHANGE", "java.awt.event.KeyEvent", true),
              })
          .put(
              "DIRECTIONALITY_SEGMENT_SEPARATOR",
              new Import[] {
                new Import("DIRECTIONALITY_SEGMENT_SEPARATOR", "java.lang.Character", true),
              })
          .put(
              "MYANMAR_EXTENDED_A",
              new Import[] {
                new Import("MYANMAR_EXTENDED_A", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "Environment",
              new Import[] {
                new Import("Environment", "org.omg.CORBA", false),
              })
          .put(
              "EMPTY_ENUMERATION",
              new Import[] {
                new Import("EMPTY_ENUMERATION", "javax.swing.tree.DefaultMutableTreeNode", true),
              })
          .put(
              "CommandMap",
              new Import[] {
                new Import("CommandMap", "javax.activation", false),
              })
          .put(
              "ISO_B4_ENVELOPE",
              new Import[] {
                new Import("ISO_B4_ENVELOPE", "java.awt.PageAttributes.MediaType", true),
              })
          .put(
              "LARGE_SCALE",
              new Import[] {
                new Import("LARGE_SCALE", "javax.swing.plaf.nimbus.NimbusStyle", true),
              })
          .put(
              "floorMod",
              new Import[] {
                new Import("floorMod", "java.lang.Math", true),
                new Import("floorMod", "java.lang.StrictMath", true),
              })
          .put(
              "RemoteObjectInvocationHandler",
              new Import[] {
                new Import("RemoteObjectInvocationHandler", "java.rmi.server", false),
              })
          .put(
              "HORIZONTAL_SCROLLBAR_POLICY",
              new Import[] {
                new Import("HORIZONTAL_SCROLLBAR_POLICY", "javax.swing.ScrollPaneConstants", true),
              })
          .put(
              "USEMAP",
              new Import[] {
                new Import("USEMAP", "javax.swing.text.html.HTML.Attribute", true),
              })
          .put(
              "CharHolder",
              new Import[] {
                new Import("CharHolder", "org.omg.CORBA", false),
              })
          .put(
              "Arc2D",
              new Import[] {
                new Import("Arc2D", "java.awt.geom", false),
              })
          .put(
              "Source",
              new Import[] {
                new Import("Source", "javax.xml.transform", false),
              })
          .put(
              "STANDARD_INPUT_TYPE",
              new Import[] {
                new Import("STANDARD_INPUT_TYPE", "javax.imageio.spi.ImageReaderSpi", true),
              })
          .put(
              "INVITE_ENVELOPE",
              new Import[] {
                new Import("INVITE_ENVELOPE", "java.awt.PageAttributes.MediaType", true),
              })
          .put(
              "RuntimeException",
              new Import[] {
                new Import("RuntimeException", "java.lang", false),
              })
          .put(
              "FlavorTable",
              new Import[] {
                new Import("FlavorTable", "java.awt.datatransfer", false),
              })
          .put(
              "TAG_MORT",
              new Import[] {
                new Import("TAG_MORT", "java.awt.font.OpenType", true),
              })
          .put(
              "TYPE_DOUBLE",
              new Import[] {
                new Import("TYPE_DOUBLE", "java.awt.image.DataBuffer", true),
              })
          .put(
              "UNSET",
              new Import[] {
                new Import("UNSET", "javax.swing.Spring", true),
              })
          .put(
              "VK_AGAIN",
              new Import[] {
                new Import("VK_AGAIN", "java.awt.event.KeyEvent", true),
              })
          .put(
              "UNSUPPORTED_EMPTY_COLLECTION",
              new Import[] {
                new Import("UNSUPPORTED_EMPTY_COLLECTION", "java.security.Policy", true),
              })
          .put(
              "ofEpochDay",
              new Import[] {
                new Import("ofEpochDay", "java.time.LocalDate", true),
              })
          .put(
              "NoContext",
              new Import[] {
                new Import("NoContext", "org.omg.PortableServer.CurrentPackage", false),
              })
          .put(
              "MONGOLIAN",
              new Import[] {
                new Import("MONGOLIAN", "java.awt.font.NumericShaper", true),
                new Import("MONGOLIAN", "java.lang.Character.UnicodeBlock", true),
              })
          .put(
              "ISO_OFFSET_TIME",
              new Import[] {
                new Import("ISO_OFFSET_TIME", "java.time.format.DateTimeFormatter", true),
              })
          .put(
              "CodeSets",
              new Import[] {
                new Import("CodeSets", "org.omg.IOP", false),
              })
          .put(
              "endParagraphAction",
              new Import[] {
                new Import("endParagraphAction", "javax.swing.text.DefaultEditorKit", true),
              })
          .put(
              "Service",
              new Import[] {
                new Import("Service", "java.security.Provider", false),
                new Import("Service", "javax.xml.ws", false),
              })
          .put(
              "EntityResolver2",
              new Import[] {
                new Import("EntityResolver2", "org.xml.sax.ext", false),
              })
          .put(
              "PERSIST",
              new Import[] {
                new Import("PERSIST", "javax.swing.JFormattedTextField", true),
              })
          .put(
              "LongAccumulator",
              new Import[] {
                new Import("LongAccumulator", "java.util.concurrent.atomic", false),
              })
          .put(
              "StyledEditorKit",
              new Import[] {
                new Import("StyledEditorKit", "javax.swing.text", false),
              })
          .put(
              "VK_ACCEPT",
              new Import[] {
                new Import("VK_ACCEPT", "java.awt.event.KeyEvent", true),
              })
          .put(
              "FeatureDescriptor",
              new Import[] {
                new Import("FeatureDescriptor", "java.beans", false),
              })
          .put(
              "copyAction",
              new Import[] {
                new Import("copyAction", "javax.swing.text.DefaultEditorKit", true),
              })
          .put(
              "Future",
              new Import[] {
                new Import("Future", "java.util.concurrent", false),
              })
          .put(
              "getContext",
              new Import[] {
                new Import("getContext", "java.security.AccessController", true),
              })
          .put(
              "getFocusColor",
              new Import[] {
                new Import("getFocusColor", "javax.swing.plaf.metal.MetalLookAndFeel", true),
              })
          .build();
}
